/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.reports.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.reports.types.PostV1ReportsFinancialStatementsRequestCategory;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1ReportsFinancialStatementsRequest.Builder.class
)
public final class PostV1ReportsFinancialStatementsRequest {
  private final String fromDate;

  private final String toDate;

  private final Optional<PostV1ReportsFinancialStatementsRequestCategory> category;

  private final Map<String, Object> additionalProperties;

  private PostV1ReportsFinancialStatementsRequest(String fromDate, String toDate,
      Optional<PostV1ReportsFinancialStatementsRequestCategory> category,
      Map<String, Object> additionalProperties) {
    this.fromDate = fromDate;
    this.toDate = toDate;
    this.category = category;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("fromDate")
  public String getFromDate() {
    return fromDate;
  }

  @JsonProperty("toDate")
  public String getToDate() {
    return toDate;
  }

  @JsonProperty("category")
  public Optional<PostV1ReportsFinancialStatementsRequestCategory> getCategory() {
    return category;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1ReportsFinancialStatementsRequest && equalTo((PostV1ReportsFinancialStatementsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1ReportsFinancialStatementsRequest other) {
    return fromDate.equals(other.fromDate) && toDate.equals(other.toDate) && category.equals(other.category);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fromDate, this.toDate, this.category);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FromDateStage builder() {
    return new Builder();
  }

  public interface FromDateStage {
    ToDateStage fromDate(@NotNull String fromDate);

    Builder from(PostV1ReportsFinancialStatementsRequest other);
  }

  public interface ToDateStage {
    _FinalStage toDate(@NotNull String toDate);
  }

  public interface _FinalStage {
    PostV1ReportsFinancialStatementsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage category(Optional<PostV1ReportsFinancialStatementsRequestCategory> category);

    _FinalStage category(PostV1ReportsFinancialStatementsRequestCategory category);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FromDateStage, ToDateStage, _FinalStage {
    private String fromDate;

    private String toDate;

    private Optional<PostV1ReportsFinancialStatementsRequestCategory> category = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1ReportsFinancialStatementsRequest other) {
      fromDate(other.getFromDate());
      toDate(other.getToDate());
      category(other.getCategory());
      return this;
    }

    @java.lang.Override
    @JsonSetter("fromDate")
    public ToDateStage fromDate(@NotNull String fromDate) {
      this.fromDate = Objects.requireNonNull(fromDate, "fromDate must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("toDate")
    public _FinalStage toDate(@NotNull String toDate) {
      this.toDate = Objects.requireNonNull(toDate, "toDate must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage category(PostV1ReportsFinancialStatementsRequestCategory category) {
      this.category = Optional.ofNullable(category);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "category",
        nulls = Nulls.SKIP
    )
    public _FinalStage category(
        Optional<PostV1ReportsFinancialStatementsRequestCategory> category) {
      this.category = category;
      return this;
    }

    @java.lang.Override
    public PostV1ReportsFinancialStatementsRequest build() {
      return new PostV1ReportsFinancialStatementsRequest(fromDate, toDate, category, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
