/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.inventory.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1InventoryReorderRulesListResponseRowsItem.Builder.class
)
public final class PostV1InventoryReorderRulesListResponseRowsItem {
  private final String id;

  private final String itemId;

  private final Optional<String> warehouseId;

  private final String minQty;

  private final Optional<String> reorderQty;

  private final boolean isActive;

  private final Optional<String> notes;

  private final String createdAt;

  private final String updatedAt;

  private final Map<String, Object> additionalProperties;

  private PostV1InventoryReorderRulesListResponseRowsItem(String id, String itemId,
      Optional<String> warehouseId, String minQty, Optional<String> reorderQty, boolean isActive,
      Optional<String> notes, String createdAt, String updatedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.itemId = itemId;
    this.warehouseId = warehouseId;
    this.minQty = minQty;
    this.reorderQty = reorderQty;
    this.isActive = isActive;
    this.notes = notes;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("itemId")
  public String getItemId() {
    return itemId;
  }

  @JsonIgnore
  public Optional<String> getWarehouseId() {
    if (warehouseId == null) {
      return Optional.empty();
    }
    return warehouseId;
  }

  @JsonProperty("minQty")
  public String getMinQty() {
    return minQty;
  }

  @JsonIgnore
  public Optional<String> getReorderQty() {
    if (reorderQty == null) {
      return Optional.empty();
    }
    return reorderQty;
  }

  @JsonProperty("isActive")
  public boolean getIsActive() {
    return isActive;
  }

  @JsonIgnore
  public Optional<String> getNotes() {
    if (notes == null) {
      return Optional.empty();
    }
    return notes;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updatedAt")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("warehouseId")
  private Optional<String> _getWarehouseId() {
    return warehouseId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("reorderQty")
  private Optional<String> _getReorderQty() {
    return reorderQty;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("notes")
  private Optional<String> _getNotes() {
    return notes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1InventoryReorderRulesListResponseRowsItem && equalTo((PostV1InventoryReorderRulesListResponseRowsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1InventoryReorderRulesListResponseRowsItem other) {
    return id.equals(other.id) && itemId.equals(other.itemId) && warehouseId.equals(other.warehouseId) && minQty.equals(other.minQty) && reorderQty.equals(other.reorderQty) && isActive == other.isActive && notes.equals(other.notes) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.itemId, this.warehouseId, this.minQty, this.reorderQty, this.isActive, this.notes, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    ItemIdStage id(@NotNull String id);

    Builder from(PostV1InventoryReorderRulesListResponseRowsItem other);
  }

  public interface ItemIdStage {
    MinQtyStage itemId(@NotNull String itemId);
  }

  public interface MinQtyStage {
    IsActiveStage minQty(@NotNull String minQty);
  }

  public interface IsActiveStage {
    CreatedAtStage isActive(boolean isActive);
  }

  public interface CreatedAtStage {
    UpdatedAtStage createdAt(@NotNull String createdAt);
  }

  public interface UpdatedAtStage {
    _FinalStage updatedAt(@NotNull String updatedAt);
  }

  public interface _FinalStage {
    PostV1InventoryReorderRulesListResponseRowsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage warehouseId(Optional<String> warehouseId);

    _FinalStage warehouseId(String warehouseId);

    _FinalStage warehouseId(Nullable<String> warehouseId);

    _FinalStage reorderQty(Optional<String> reorderQty);

    _FinalStage reorderQty(String reorderQty);

    _FinalStage reorderQty(Nullable<String> reorderQty);

    _FinalStage notes(Optional<String> notes);

    _FinalStage notes(String notes);

    _FinalStage notes(Nullable<String> notes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, ItemIdStage, MinQtyStage, IsActiveStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
    private String id;

    private String itemId;

    private String minQty;

    private boolean isActive;

    private String createdAt;

    private String updatedAt;

    private Optional<String> notes = Optional.empty();

    private Optional<String> reorderQty = Optional.empty();

    private Optional<String> warehouseId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1InventoryReorderRulesListResponseRowsItem other) {
      id(other.getId());
      itemId(other.getItemId());
      warehouseId(other.getWarehouseId());
      minQty(other.getMinQty());
      reorderQty(other.getReorderQty());
      isActive(other.getIsActive());
      notes(other.getNotes());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public ItemIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("itemId")
    public MinQtyStage itemId(@NotNull String itemId) {
      this.itemId = Objects.requireNonNull(itemId, "itemId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("minQty")
    public IsActiveStage minQty(@NotNull String minQty) {
      this.minQty = Objects.requireNonNull(minQty, "minQty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("isActive")
    public CreatedAtStage isActive(boolean isActive) {
      this.isActive = isActive;
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public UpdatedAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updatedAt")
    public _FinalStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(Nullable<String> notes) {
      if (notes.isNull()) {
        this.notes = null;
      }
      else if (notes.isEmpty()) {
        this.notes = Optional.empty();
      }
      else {
        this.notes = Optional.of(notes.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(String notes) {
      this.notes = Optional.ofNullable(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(Optional<String> notes) {
      this.notes = notes;
      return this;
    }

    @java.lang.Override
    public _FinalStage reorderQty(Nullable<String> reorderQty) {
      if (reorderQty.isNull()) {
        this.reorderQty = null;
      }
      else if (reorderQty.isEmpty()) {
        this.reorderQty = Optional.empty();
      }
      else {
        this.reorderQty = Optional.of(reorderQty.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage reorderQty(String reorderQty) {
      this.reorderQty = Optional.ofNullable(reorderQty);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "reorderQty",
        nulls = Nulls.SKIP
    )
    public _FinalStage reorderQty(Optional<String> reorderQty) {
      this.reorderQty = reorderQty;
      return this;
    }

    @java.lang.Override
    public _FinalStage warehouseId(Nullable<String> warehouseId) {
      if (warehouseId.isNull()) {
        this.warehouseId = null;
      }
      else if (warehouseId.isEmpty()) {
        this.warehouseId = Optional.empty();
      }
      else {
        this.warehouseId = Optional.of(warehouseId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage warehouseId(String warehouseId) {
      this.warehouseId = Optional.ofNullable(warehouseId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warehouseId",
        nulls = Nulls.SKIP
    )
    public _FinalStage warehouseId(Optional<String> warehouseId) {
      this.warehouseId = warehouseId;
      return this;
    }

    @java.lang.Override
    public PostV1InventoryReorderRulesListResponseRowsItem build() {
      return new PostV1InventoryReorderRulesListResponseRowsItem(id, itemId, warehouseId, minQty, reorderQty, isActive, notes, createdAt, updatedAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
