/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.inventory.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1InventoryLandedCostsListRequestFilterItemOp {
  public static final PostV1InventoryLandedCostsListRequestFilterItemOp CONTAINS = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.CONTAINS, "contains");

  public static final PostV1InventoryLandedCostsListRequestFilterItemOp GTE = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.GTE, "gte");

  public static final PostV1InventoryLandedCostsListRequestFilterItemOp IN = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.IN, "in");

  public static final PostV1InventoryLandedCostsListRequestFilterItemOp EQ = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.EQ, "eq");

  public static final PostV1InventoryLandedCostsListRequestFilterItemOp NE = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.NE, "ne");

  public static final PostV1InventoryLandedCostsListRequestFilterItemOp LTE = new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.LTE, "lte");

  private final Value value;

  private final String string;

  PostV1InventoryLandedCostsListRequestFilterItemOp(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1InventoryLandedCostsListRequestFilterItemOp && this.string.equals(((PostV1InventoryLandedCostsListRequestFilterItemOp) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CONTAINS:
        return visitor.visitContains();
      case GTE:
        return visitor.visitGte();
      case IN:
        return visitor.visitIn();
      case EQ:
        return visitor.visitEq();
      case NE:
        return visitor.visitNe();
      case LTE:
        return visitor.visitLte();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1InventoryLandedCostsListRequestFilterItemOp valueOf(String value) {
    switch (value) {
      case "contains":
        return CONTAINS;
      case "gte":
        return GTE;
      case "in":
        return IN;
      case "eq":
        return EQ;
      case "ne":
        return NE;
      case "lte":
        return LTE;
      default:
        return new PostV1InventoryLandedCostsListRequestFilterItemOp(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    EQ,

    NE,

    CONTAINS,

    GTE,

    LTE,

    IN,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitEq();

    T visitNe();

    T visitContains();

    T visitGte();

    T visitLte();

    T visitIn();

    T visitUnknown(String unknownType);
  }
}
