/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.reports.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GlDetailReportsResponseAccount.Builder.class
)
public final class GlDetailReportsResponseAccount {
  private final String code;

  private final String name;

  private final String type;

  private final Map<String, Object> additionalProperties;

  private GlDetailReportsResponseAccount(String code, String name, String type,
      Map<String, Object> additionalProperties) {
    this.code = code;
    this.name = name;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("code")
  public String getCode() {
    return code;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("type")
  public String getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GlDetailReportsResponseAccount && equalTo((GlDetailReportsResponseAccount) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GlDetailReportsResponseAccount other) {
    return code.equals(other.code) && name.equals(other.name) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.name, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CodeStage builder() {
    return new Builder();
  }

  public interface CodeStage {
    NameStage code(@NotNull String code);

    Builder from(GlDetailReportsResponseAccount other);
  }

  public interface NameStage {
    TypeStage name(@NotNull String name);
  }

  public interface TypeStage {
    _FinalStage type(@NotNull String type);
  }

  public interface _FinalStage {
    GlDetailReportsResponseAccount build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CodeStage, NameStage, TypeStage, _FinalStage {
    private String code;

    private String name;

    private String type;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GlDetailReportsResponseAccount other) {
      code(other.getCode());
      name(other.getName());
      type(other.getType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("code")
    public NameStage code(@NotNull String code) {
      this.code = Objects.requireNonNull(code, "code must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public TypeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull String type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public GlDetailReportsResponseAccount build() {
      return new GlDetailReportsResponseAccount(code, name, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
