/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.reports.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StockBalanceReportsResponse.Builder.class
)
public final class StockBalanceReportsResponse {
  private final String asOf;

  private final List<StockBalanceReportsResponseRowsItem> rows;

  private final String totalValue;

  private final Map<String, Object> additionalProperties;

  private StockBalanceReportsResponse(String asOf, List<StockBalanceReportsResponseRowsItem> rows,
      String totalValue, Map<String, Object> additionalProperties) {
    this.asOf = asOf;
    this.rows = rows;
    this.totalValue = totalValue;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("asOf")
  public String getAsOf() {
    return asOf;
  }

  @JsonProperty("rows")
  public List<StockBalanceReportsResponseRowsItem> getRows() {
    return rows;
  }

  @JsonProperty("totalValue")
  public String getTotalValue() {
    return totalValue;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StockBalanceReportsResponse && equalTo((StockBalanceReportsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StockBalanceReportsResponse other) {
    return asOf.equals(other.asOf) && rows.equals(other.rows) && totalValue.equals(other.totalValue);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.asOf, this.rows, this.totalValue);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AsOfStage builder() {
    return new Builder();
  }

  public interface AsOfStage {
    TotalValueStage asOf(@NotNull String asOf);

    Builder from(StockBalanceReportsResponse other);
  }

  public interface TotalValueStage {
    _FinalStage totalValue(@NotNull String totalValue);
  }

  public interface _FinalStage {
    StockBalanceReportsResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage rows(List<StockBalanceReportsResponseRowsItem> rows);

    _FinalStage addRows(StockBalanceReportsResponseRowsItem rows);

    _FinalStage addAllRows(List<StockBalanceReportsResponseRowsItem> rows);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AsOfStage, TotalValueStage, _FinalStage {
    private String asOf;

    private String totalValue;

    private List<StockBalanceReportsResponseRowsItem> rows = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(StockBalanceReportsResponse other) {
      asOf(other.getAsOf());
      rows(other.getRows());
      totalValue(other.getTotalValue());
      return this;
    }

    @java.lang.Override
    @JsonSetter("asOf")
    public TotalValueStage asOf(@NotNull String asOf) {
      this.asOf = Objects.requireNonNull(asOf, "asOf must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalValue")
    public _FinalStage totalValue(@NotNull String totalValue) {
      this.totalValue = Objects.requireNonNull(totalValue, "totalValue must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllRows(List<StockBalanceReportsResponseRowsItem> rows) {
      if (rows != null) {
        this.rows.addAll(rows);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addRows(StockBalanceReportsResponseRowsItem rows) {
      this.rows.add(rows);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "rows",
        nulls = Nulls.SKIP
    )
    public _FinalStage rows(List<StockBalanceReportsResponseRowsItem> rows) {
      this.rows.clear();
      if (rows != null) {
        this.rows.addAll(rows);
      }
      return this;
    }

    @java.lang.Override
    public StockBalanceReportsResponse build() {
      return new StockBalanceReportsResponse(asOf, rows, totalValue, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
