/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.sales.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ActsUpdateSalesRequestType {
  public static final ActsUpdateSalesRequestType SERVICES = new ActsUpdateSalesRequestType(Value.SERVICES, "services");

  public static final ActsUpdateSalesRequestType GOODS = new ActsUpdateSalesRequestType(Value.GOODS, "goods");

  private final Value value;

  private final String string;

  ActsUpdateSalesRequestType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ActsUpdateSalesRequestType && this.string.equals(((ActsUpdateSalesRequestType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SERVICES:
        return visitor.visitServices();
      case GOODS:
        return visitor.visitGoods();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ActsUpdateSalesRequestType valueOf(String value) {
    switch (value) {
      case "services":
        return SERVICES;
      case "goods":
        return GOODS;
      default:
        return new ActsUpdateSalesRequestType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    GOODS,

    SERVICES,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitGoods();

    T visitServices();

    T visitUnknown(String unknownType);
  }
}
