/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.sales.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InvoicesEinvoiceSendSalesResponse.Builder.class
)
public final class InvoicesEinvoiceSendSalesResponse {
  private final boolean sent;

  private final String system;

  private final String format;

  private final InvoicesEinvoiceSendSalesResponseTransport transport;

  private final String messageId;

  private final Optional<String> nationalNumber;

  private final InvoicesEinvoiceSendSalesResponseStatus status;

  private final Optional<String> detail;

  private final Optional<String> fileId;

  private final List<String> warnings;

  private final Map<String, Object> additionalProperties;

  private InvoicesEinvoiceSendSalesResponse(boolean sent, String system, String format,
      InvoicesEinvoiceSendSalesResponseTransport transport, String messageId,
      Optional<String> nationalNumber, InvoicesEinvoiceSendSalesResponseStatus status,
      Optional<String> detail, Optional<String> fileId, List<String> warnings,
      Map<String, Object> additionalProperties) {
    this.sent = sent;
    this.system = system;
    this.format = format;
    this.transport = transport;
    this.messageId = messageId;
    this.nationalNumber = nationalNumber;
    this.status = status;
    this.detail = detail;
    this.fileId = fileId;
    this.warnings = warnings;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("sent")
  public boolean getSent() {
    return sent;
  }

  @JsonProperty("system")
  public String getSystem() {
    return system;
  }

  @JsonProperty("format")
  public String getFormat() {
    return format;
  }

  @JsonProperty("transport")
  public InvoicesEinvoiceSendSalesResponseTransport getTransport() {
    return transport;
  }

  @JsonProperty("messageId")
  public String getMessageId() {
    return messageId;
  }

  @JsonIgnore
  public Optional<String> getNationalNumber() {
    if (nationalNumber == null) {
      return Optional.empty();
    }
    return nationalNumber;
  }

  @JsonProperty("status")
  public InvoicesEinvoiceSendSalesResponseStatus getStatus() {
    return status;
  }

  @JsonIgnore
  public Optional<String> getDetail() {
    if (detail == null) {
      return Optional.empty();
    }
    return detail;
  }

  @JsonIgnore
  public Optional<String> getFileId() {
    if (fileId == null) {
      return Optional.empty();
    }
    return fileId;
  }

  @JsonProperty("warnings")
  public List<String> getWarnings() {
    return warnings;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("nationalNumber")
  private Optional<String> _getNationalNumber() {
    return nationalNumber;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("detail")
  private Optional<String> _getDetail() {
    return detail;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("fileId")
  private Optional<String> _getFileId() {
    return fileId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InvoicesEinvoiceSendSalesResponse && equalTo((InvoicesEinvoiceSendSalesResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InvoicesEinvoiceSendSalesResponse other) {
    return sent == other.sent && system.equals(other.system) && format.equals(other.format) && transport.equals(other.transport) && messageId.equals(other.messageId) && nationalNumber.equals(other.nationalNumber) && status.equals(other.status) && detail.equals(other.detail) && fileId.equals(other.fileId) && warnings.equals(other.warnings);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.sent, this.system, this.format, this.transport, this.messageId, this.nationalNumber, this.status, this.detail, this.fileId, this.warnings);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SentStage builder() {
    return new Builder();
  }

  public interface SentStage {
    SystemStage sent(boolean sent);

    Builder from(InvoicesEinvoiceSendSalesResponse other);
  }

  public interface SystemStage {
    FormatStage system(@NotNull String system);
  }

  public interface FormatStage {
    TransportStage format(@NotNull String format);
  }

  public interface TransportStage {
    MessageIdStage transport(@NotNull InvoicesEinvoiceSendSalesResponseTransport transport);
  }

  public interface MessageIdStage {
    StatusStage messageId(@NotNull String messageId);
  }

  public interface StatusStage {
    _FinalStage status(@NotNull InvoicesEinvoiceSendSalesResponseStatus status);
  }

  public interface _FinalStage {
    InvoicesEinvoiceSendSalesResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage nationalNumber(Optional<String> nationalNumber);

    _FinalStage nationalNumber(String nationalNumber);

    _FinalStage nationalNumber(Nullable<String> nationalNumber);

    _FinalStage detail(Optional<String> detail);

    _FinalStage detail(String detail);

    _FinalStage detail(Nullable<String> detail);

    _FinalStage fileId(Optional<String> fileId);

    _FinalStage fileId(String fileId);

    _FinalStage fileId(Nullable<String> fileId);

    _FinalStage warnings(List<String> warnings);

    _FinalStage addWarnings(String warnings);

    _FinalStage addAllWarnings(List<String> warnings);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SentStage, SystemStage, FormatStage, TransportStage, MessageIdStage, StatusStage, _FinalStage {
    private boolean sent;

    private String system;

    private String format;

    private InvoicesEinvoiceSendSalesResponseTransport transport;

    private String messageId;

    private InvoicesEinvoiceSendSalesResponseStatus status;

    private List<String> warnings = new ArrayList<>();

    private Optional<String> fileId = Optional.empty();

    private Optional<String> detail = Optional.empty();

    private Optional<String> nationalNumber = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(InvoicesEinvoiceSendSalesResponse other) {
      sent(other.getSent());
      system(other.getSystem());
      format(other.getFormat());
      transport(other.getTransport());
      messageId(other.getMessageId());
      nationalNumber(other.getNationalNumber());
      status(other.getStatus());
      detail(other.getDetail());
      fileId(other.getFileId());
      warnings(other.getWarnings());
      return this;
    }

    @java.lang.Override
    @JsonSetter("sent")
    public SystemStage sent(boolean sent) {
      this.sent = sent;
      return this;
    }

    @java.lang.Override
    @JsonSetter("system")
    public FormatStage system(@NotNull String system) {
      this.system = Objects.requireNonNull(system, "system must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("format")
    public TransportStage format(@NotNull String format) {
      this.format = Objects.requireNonNull(format, "format must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("transport")
    public MessageIdStage transport(@NotNull InvoicesEinvoiceSendSalesResponseTransport transport) {
      this.transport = Objects.requireNonNull(transport, "transport must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("messageId")
    public StatusStage messageId(@NotNull String messageId) {
      this.messageId = Objects.requireNonNull(messageId, "messageId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull InvoicesEinvoiceSendSalesResponseStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllWarnings(List<String> warnings) {
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addWarnings(String warnings) {
      this.warnings.add(warnings);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warnings",
        nulls = Nulls.SKIP
    )
    public _FinalStage warnings(List<String> warnings) {
      this.warnings.clear();
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage fileId(Nullable<String> fileId) {
      if (fileId.isNull()) {
        this.fileId = null;
      }
      else if (fileId.isEmpty()) {
        this.fileId = Optional.empty();
      }
      else {
        this.fileId = Optional.of(fileId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage fileId(String fileId) {
      this.fileId = Optional.ofNullable(fileId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "fileId",
        nulls = Nulls.SKIP
    )
    public _FinalStage fileId(Optional<String> fileId) {
      this.fileId = fileId;
      return this;
    }

    @java.lang.Override
    public _FinalStage detail(Nullable<String> detail) {
      if (detail.isNull()) {
        this.detail = null;
      }
      else if (detail.isEmpty()) {
        this.detail = Optional.empty();
      }
      else {
        this.detail = Optional.of(detail.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage detail(String detail) {
      this.detail = Optional.ofNullable(detail);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "detail",
        nulls = Nulls.SKIP
    )
    public _FinalStage detail(Optional<String> detail) {
      this.detail = detail;
      return this;
    }

    @java.lang.Override
    public _FinalStage nationalNumber(Nullable<String> nationalNumber) {
      if (nationalNumber.isNull()) {
        this.nationalNumber = null;
      }
      else if (nationalNumber.isEmpty()) {
        this.nationalNumber = Optional.empty();
      }
      else {
        this.nationalNumber = Optional.of(nationalNumber.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage nationalNumber(String nationalNumber) {
      this.nationalNumber = Optional.ofNullable(nationalNumber);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "nationalNumber",
        nulls = Nulls.SKIP
    )
    public _FinalStage nationalNumber(Optional<String> nationalNumber) {
      this.nationalNumber = nationalNumber;
      return this;
    }

    @java.lang.Override
    public InvoicesEinvoiceSendSalesResponse build() {
      return new InvoicesEinvoiceSendSalesResponse(sent, system, format, transport, messageId, nationalNumber, status, detail, fileId, warnings, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
