/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.sales.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class InvoicesIssueSalesResponsePaymentStatus {
  public static final InvoicesIssueSalesResponsePaymentStatus PARTIAL = new InvoicesIssueSalesResponsePaymentStatus(Value.PARTIAL, "partial");

  public static final InvoicesIssueSalesResponsePaymentStatus PAID = new InvoicesIssueSalesResponsePaymentStatus(Value.PAID, "paid");

  public static final InvoicesIssueSalesResponsePaymentStatus UNPAID = new InvoicesIssueSalesResponsePaymentStatus(Value.UNPAID, "unpaid");

  private final Value value;

  private final String string;

  InvoicesIssueSalesResponsePaymentStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof InvoicesIssueSalesResponsePaymentStatus && this.string.equals(((InvoicesIssueSalesResponsePaymentStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PARTIAL:
        return visitor.visitPartial();
      case PAID:
        return visitor.visitPaid();
      case UNPAID:
        return visitor.visitUnpaid();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static InvoicesIssueSalesResponsePaymentStatus valueOf(String value) {
    switch (value) {
      case "partial":
        return PARTIAL;
      case "paid":
        return PAID;
      case "unpaid":
        return UNPAID;
      default:
        return new InvoicesIssueSalesResponsePaymentStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    UNPAID,

    PARTIAL,

    PAID,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUnpaid();

    T visitPartial();

    T visitPaid();

    T visitUnknown(String unknownType);
  }
}
