/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.sales.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class InvoicesApplyAdvanceSalesResponseType {
  public static final InvoicesApplyAdvanceSalesResponseType CREDIT_NOTE = new InvoicesApplyAdvanceSalesResponseType(Value.CREDIT_NOTE, "credit_note");

  public static final InvoicesApplyAdvanceSalesResponseType ADVANCE = new InvoicesApplyAdvanceSalesResponseType(Value.ADVANCE, "advance");

  public static final InvoicesApplyAdvanceSalesResponseType PROFORMA = new InvoicesApplyAdvanceSalesResponseType(Value.PROFORMA, "proforma");

  public static final InvoicesApplyAdvanceSalesResponseType INVOICE = new InvoicesApplyAdvanceSalesResponseType(Value.INVOICE, "invoice");

  private final Value value;

  private final String string;

  InvoicesApplyAdvanceSalesResponseType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof InvoicesApplyAdvanceSalesResponseType && this.string.equals(((InvoicesApplyAdvanceSalesResponseType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CREDIT_NOTE:
        return visitor.visitCreditNote();
      case ADVANCE:
        return visitor.visitAdvance();
      case PROFORMA:
        return visitor.visitProforma();
      case INVOICE:
        return visitor.visitInvoice();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static InvoicesApplyAdvanceSalesResponseType valueOf(String value) {
    switch (value) {
      case "credit_note":
        return CREDIT_NOTE;
      case "advance":
        return ADVANCE;
      case "proforma":
        return PROFORMA;
      case "invoice":
        return INVOICE;
      default:
        return new InvoicesApplyAdvanceSalesResponseType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INVOICE,

    CREDIT_NOTE,

    PROFORMA,

    ADVANCE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInvoice();

    T visitCreditNote();

    T visitProforma();

    T visitAdvance();

    T visitUnknown(String unknownType);
  }
}
