/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.purchases.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1PurchasesInvoicesMatchResponseStatus {
  public static final PostV1PurchasesInvoicesMatchResponseStatus MATCHED = new PostV1PurchasesInvoicesMatchResponseStatus(Value.MATCHED, "matched");

  public static final PostV1PurchasesInvoicesMatchResponseStatus MISMATCHED = new PostV1PurchasesInvoicesMatchResponseStatus(Value.MISMATCHED, "mismatched");

  private final Value value;

  private final String string;

  PostV1PurchasesInvoicesMatchResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1PurchasesInvoicesMatchResponseStatus && this.string.equals(((PostV1PurchasesInvoicesMatchResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MATCHED:
        return visitor.visitMatched();
      case MISMATCHED:
        return visitor.visitMismatched();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1PurchasesInvoicesMatchResponseStatus valueOf(String value) {
    switch (value) {
      case "matched":
        return MATCHED;
      case "mismatched":
        return MISMATCHED;
      default:
        return new PostV1PurchasesInvoicesMatchResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MATCHED,

    MISMATCHED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMatched();

    T visitMismatched();

    T visitUnknown(String unknownType);
  }
}
