/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.audit.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1AuditListResponseRowsItem.Builder.class
)
public final class PostV1AuditListResponseRowsItem {
  private final long id;

  private final PostV1AuditListResponseRowsItemActorType actorType;

  private final Optional<String> actorId;

  private final String action;

  private final String entity;

  private final Optional<String> entityId;

  private final Optional<Object> diff;

  private final String createdAt;

  private final Map<String, Object> additionalProperties;

  private PostV1AuditListResponseRowsItem(long id,
      PostV1AuditListResponseRowsItemActorType actorType, Optional<String> actorId, String action,
      String entity, Optional<String> entityId, Optional<Object> diff, String createdAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.actorType = actorType;
    this.actorId = actorId;
    this.action = action;
    this.entity = entity;
    this.entityId = entityId;
    this.diff = diff;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public long getId() {
    return id;
  }

  @JsonProperty("actorType")
  public PostV1AuditListResponseRowsItemActorType getActorType() {
    return actorType;
  }

  @JsonIgnore
  public Optional<String> getActorId() {
    if (actorId == null) {
      return Optional.empty();
    }
    return actorId;
  }

  @JsonProperty("action")
  public String getAction() {
    return action;
  }

  @JsonProperty("entity")
  public String getEntity() {
    return entity;
  }

  @JsonIgnore
  public Optional<String> getEntityId() {
    if (entityId == null) {
      return Optional.empty();
    }
    return entityId;
  }

  @JsonIgnore
  public Optional<Object> getDiff() {
    if (diff == null) {
      return Optional.empty();
    }
    return diff;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("actorId")
  private Optional<String> _getActorId() {
    return actorId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("entityId")
  private Optional<String> _getEntityId() {
    return entityId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("diff")
  private Optional<Object> _getDiff() {
    return diff;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1AuditListResponseRowsItem && equalTo((PostV1AuditListResponseRowsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1AuditListResponseRowsItem other) {
    return id == other.id && actorType.equals(other.actorType) && actorId.equals(other.actorId) && action.equals(other.action) && entity.equals(other.entity) && entityId.equals(other.entityId) && diff.equals(other.diff) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.actorType, this.actorId, this.action, this.entity, this.entityId, this.diff, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    ActorTypeStage id(long id);

    Builder from(PostV1AuditListResponseRowsItem other);
  }

  public interface ActorTypeStage {
    ActionStage actorType(@NotNull PostV1AuditListResponseRowsItemActorType actorType);
  }

  public interface ActionStage {
    EntityStage action(@NotNull String action);
  }

  public interface EntityStage {
    CreatedAtStage entity(@NotNull String entity);
  }

  public interface CreatedAtStage {
    _FinalStage createdAt(@NotNull String createdAt);
  }

  public interface _FinalStage {
    PostV1AuditListResponseRowsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage actorId(Optional<String> actorId);

    _FinalStage actorId(String actorId);

    _FinalStage actorId(Nullable<String> actorId);

    _FinalStage entityId(Optional<String> entityId);

    _FinalStage entityId(String entityId);

    _FinalStage entityId(Nullable<String> entityId);

    _FinalStage diff(Optional<Object> diff);

    _FinalStage diff(Object diff);

    _FinalStage diff(Nullable<Object> diff);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, ActorTypeStage, ActionStage, EntityStage, CreatedAtStage, _FinalStage {
    private long id;

    private PostV1AuditListResponseRowsItemActorType actorType;

    private String action;

    private String entity;

    private String createdAt;

    private Optional<Object> diff = Optional.empty();

    private Optional<String> entityId = Optional.empty();

    private Optional<String> actorId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1AuditListResponseRowsItem other) {
      id(other.getId());
      actorType(other.getActorType());
      actorId(other.getActorId());
      action(other.getAction());
      entity(other.getEntity());
      entityId(other.getEntityId());
      diff(other.getDiff());
      createdAt(other.getCreatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public ActorTypeStage id(long id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    @JsonSetter("actorType")
    public ActionStage actorType(@NotNull PostV1AuditListResponseRowsItemActorType actorType) {
      this.actorType = Objects.requireNonNull(actorType, "actorType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("action")
    public EntityStage action(@NotNull String action) {
      this.action = Objects.requireNonNull(action, "action must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("entity")
    public CreatedAtStage entity(@NotNull String entity) {
      this.entity = Objects.requireNonNull(entity, "entity must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public _FinalStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage diff(Nullable<Object> diff) {
      if (diff.isNull()) {
        this.diff = null;
      }
      else if (diff.isEmpty()) {
        this.diff = Optional.empty();
      }
      else {
        this.diff = Optional.of(diff.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage diff(Object diff) {
      this.diff = Optional.ofNullable(diff);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "diff",
        nulls = Nulls.SKIP
    )
    public _FinalStage diff(Optional<Object> diff) {
      this.diff = diff;
      return this;
    }

    @java.lang.Override
    public _FinalStage entityId(Nullable<String> entityId) {
      if (entityId.isNull()) {
        this.entityId = null;
      }
      else if (entityId.isEmpty()) {
        this.entityId = Optional.empty();
      }
      else {
        this.entityId = Optional.of(entityId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage entityId(String entityId) {
      this.entityId = Optional.ofNullable(entityId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "entityId",
        nulls = Nulls.SKIP
    )
    public _FinalStage entityId(Optional<String> entityId) {
      this.entityId = entityId;
      return this;
    }

    @java.lang.Override
    public _FinalStage actorId(Nullable<String> actorId) {
      if (actorId.isNull()) {
        this.actorId = null;
      }
      else if (actorId.isEmpty()) {
        this.actorId = Optional.empty();
      }
      else {
        this.actorId = Optional.of(actorId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage actorId(String actorId) {
      this.actorId = Optional.ofNullable(actorId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "actorId",
        nulls = Nulls.SKIP
    )
    public _FinalStage actorId(Optional<String> actorId) {
      this.actorId = actorId;
      return this;
    }

    @java.lang.Override
    public PostV1AuditListResponseRowsItem build() {
      return new PostV1AuditListResponseRowsItem(id, actorType, actorId, action, entity, entityId, diff, createdAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
