/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.production.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1ProductionWorkCentersUpdateRequest.Builder.class
)
public final class PostV1ProductionWorkCentersUpdateRequest {
  private final String id;

  private final Optional<String> code;

  private final Optional<String> name;

  private final Optional<String> costPerHour;

  private final Optional<String> costAccountCode;

  private final Optional<Long> maintenanceIntervalDays;

  private final Optional<Boolean> isActive;

  private final Optional<String> notes;

  private final Map<String, Object> additionalProperties;

  private PostV1ProductionWorkCentersUpdateRequest(String id, Optional<String> code,
      Optional<String> name, Optional<String> costPerHour, Optional<String> costAccountCode,
      Optional<Long> maintenanceIntervalDays, Optional<Boolean> isActive, Optional<String> notes,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.code = code;
    this.name = name;
    this.costPerHour = costPerHour;
    this.costAccountCode = costAccountCode;
    this.maintenanceIntervalDays = maintenanceIntervalDays;
    this.isActive = isActive;
    this.notes = notes;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("code")
  public Optional<String> getCode() {
    return code;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("costPerHour")
  public Optional<String> getCostPerHour() {
    return costPerHour;
  }

  @JsonIgnore
  public Optional<String> getCostAccountCode() {
    if (costAccountCode == null) {
      return Optional.empty();
    }
    return costAccountCode;
  }

  @JsonIgnore
  public Optional<Long> getMaintenanceIntervalDays() {
    if (maintenanceIntervalDays == null) {
      return Optional.empty();
    }
    return maintenanceIntervalDays;
  }

  @JsonProperty("isActive")
  public Optional<Boolean> getIsActive() {
    return isActive;
  }

  @JsonIgnore
  public Optional<String> getNotes() {
    if (notes == null) {
      return Optional.empty();
    }
    return notes;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("costAccountCode")
  private Optional<String> _getCostAccountCode() {
    return costAccountCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("maintenanceIntervalDays")
  private Optional<Long> _getMaintenanceIntervalDays() {
    return maintenanceIntervalDays;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("notes")
  private Optional<String> _getNotes() {
    return notes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1ProductionWorkCentersUpdateRequest && equalTo((PostV1ProductionWorkCentersUpdateRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1ProductionWorkCentersUpdateRequest other) {
    return id.equals(other.id) && code.equals(other.code) && name.equals(other.name) && costPerHour.equals(other.costPerHour) && costAccountCode.equals(other.costAccountCode) && maintenanceIntervalDays.equals(other.maintenanceIntervalDays) && isActive.equals(other.isActive) && notes.equals(other.notes);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.code, this.name, this.costPerHour, this.costAccountCode, this.maintenanceIntervalDays, this.isActive, this.notes);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    _FinalStage id(@NotNull String id);

    Builder from(PostV1ProductionWorkCentersUpdateRequest other);
  }

  public interface _FinalStage {
    PostV1ProductionWorkCentersUpdateRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage code(Optional<String> code);

    _FinalStage code(String code);

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage costPerHour(Optional<String> costPerHour);

    _FinalStage costPerHour(String costPerHour);

    _FinalStage costAccountCode(Optional<String> costAccountCode);

    _FinalStage costAccountCode(String costAccountCode);

    _FinalStage costAccountCode(Nullable<String> costAccountCode);

    _FinalStage maintenanceIntervalDays(Optional<Long> maintenanceIntervalDays);

    _FinalStage maintenanceIntervalDays(Long maintenanceIntervalDays);

    _FinalStage maintenanceIntervalDays(Nullable<Long> maintenanceIntervalDays);

    _FinalStage isActive(Optional<Boolean> isActive);

    _FinalStage isActive(Boolean isActive);

    _FinalStage notes(Optional<String> notes);

    _FinalStage notes(String notes);

    _FinalStage notes(Nullable<String> notes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private String id;

    private Optional<String> notes = Optional.empty();

    private Optional<Boolean> isActive = Optional.empty();

    private Optional<Long> maintenanceIntervalDays = Optional.empty();

    private Optional<String> costAccountCode = Optional.empty();

    private Optional<String> costPerHour = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> code = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1ProductionWorkCentersUpdateRequest other) {
      id(other.getId());
      code(other.getCode());
      name(other.getName());
      costPerHour(other.getCostPerHour());
      costAccountCode(other.getCostAccountCode());
      maintenanceIntervalDays(other.getMaintenanceIntervalDays());
      isActive(other.getIsActive());
      notes(other.getNotes());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(Nullable<String> notes) {
      if (notes.isNull()) {
        this.notes = null;
      }
      else if (notes.isEmpty()) {
        this.notes = Optional.empty();
      }
      else {
        this.notes = Optional.of(notes.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(String notes) {
      this.notes = Optional.ofNullable(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(Optional<String> notes) {
      this.notes = notes;
      return this;
    }

    @java.lang.Override
    public _FinalStage isActive(Boolean isActive) {
      this.isActive = Optional.ofNullable(isActive);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "isActive",
        nulls = Nulls.SKIP
    )
    public _FinalStage isActive(Optional<Boolean> isActive) {
      this.isActive = isActive;
      return this;
    }

    @java.lang.Override
    public _FinalStage maintenanceIntervalDays(Nullable<Long> maintenanceIntervalDays) {
      if (maintenanceIntervalDays.isNull()) {
        this.maintenanceIntervalDays = null;
      }
      else if (maintenanceIntervalDays.isEmpty()) {
        this.maintenanceIntervalDays = Optional.empty();
      }
      else {
        this.maintenanceIntervalDays = Optional.of(maintenanceIntervalDays.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage maintenanceIntervalDays(Long maintenanceIntervalDays) {
      this.maintenanceIntervalDays = Optional.ofNullable(maintenanceIntervalDays);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "maintenanceIntervalDays",
        nulls = Nulls.SKIP
    )
    public _FinalStage maintenanceIntervalDays(Optional<Long> maintenanceIntervalDays) {
      this.maintenanceIntervalDays = maintenanceIntervalDays;
      return this;
    }

    @java.lang.Override
    public _FinalStage costAccountCode(Nullable<String> costAccountCode) {
      if (costAccountCode.isNull()) {
        this.costAccountCode = null;
      }
      else if (costAccountCode.isEmpty()) {
        this.costAccountCode = Optional.empty();
      }
      else {
        this.costAccountCode = Optional.of(costAccountCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage costAccountCode(String costAccountCode) {
      this.costAccountCode = Optional.ofNullable(costAccountCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "costAccountCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage costAccountCode(Optional<String> costAccountCode) {
      this.costAccountCode = costAccountCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage costPerHour(String costPerHour) {
      this.costPerHour = Optional.ofNullable(costPerHour);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "costPerHour",
        nulls = Nulls.SKIP
    )
    public _FinalStage costPerHour(Optional<String> costPerHour) {
      this.costPerHour = costPerHour;
      return this;
    }

    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public _FinalStage code(String code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public _FinalStage code(Optional<String> code) {
      this.code = code;
      return this;
    }

    @java.lang.Override
    public PostV1ProductionWorkCentersUpdateRequest build() {
      return new PostV1ProductionWorkCentersUpdateRequest(id, code, name, costPerHour, costAccountCode, maintenanceIntervalDays, isActive, notes, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
