/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.catalog.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1CatalogPriceListsItemsDeleteResponse.Builder.class
)
public final class PostV1CatalogPriceListsItemsDeleteResponse {
  private final boolean deleted;

  private final Map<String, Object> additionalProperties;

  private PostV1CatalogPriceListsItemsDeleteResponse(boolean deleted,
      Map<String, Object> additionalProperties) {
    this.deleted = deleted;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("deleted")
  public boolean getDeleted() {
    return deleted;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1CatalogPriceListsItemsDeleteResponse && equalTo((PostV1CatalogPriceListsItemsDeleteResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1CatalogPriceListsItemsDeleteResponse other) {
    return deleted == other.deleted;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.deleted);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DeletedStage builder() {
    return new Builder();
  }

  public interface DeletedStage {
    _FinalStage deleted(boolean deleted);

    Builder from(PostV1CatalogPriceListsItemsDeleteResponse other);
  }

  public interface _FinalStage {
    PostV1CatalogPriceListsItemsDeleteResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DeletedStage, _FinalStage {
    private boolean deleted;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1CatalogPriceListsItemsDeleteResponse other) {
      deleted(other.getDeleted());
      return this;
    }

    @java.lang.Override
    @JsonSetter("deleted")
    public _FinalStage deleted(boolean deleted) {
      this.deleted = deleted;
      return this;
    }

    @java.lang.Override
    public PostV1CatalogPriceListsItemsDeleteResponse build() {
      return new PostV1CatalogPriceListsItemsDeleteResponse(deleted, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
