/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.account.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1AccountExportResponseSessionsItem.Builder.class
)
public final class PostV1AccountExportResponseSessionsItem {
  private final String id;

  private final Optional<String> companyId;

  private final Optional<String> ipAddress;

  private final Optional<String> userAgent;

  private final Optional<String> lastSeenAt;

  private final String createdAt;

  private final String expiresAt;

  private final boolean current;

  private final Map<String, Object> additionalProperties;

  private PostV1AccountExportResponseSessionsItem(String id, Optional<String> companyId,
      Optional<String> ipAddress, Optional<String> userAgent, Optional<String> lastSeenAt,
      String createdAt, String expiresAt, boolean current,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.companyId = companyId;
    this.ipAddress = ipAddress;
    this.userAgent = userAgent;
    this.lastSeenAt = lastSeenAt;
    this.createdAt = createdAt;
    this.expiresAt = expiresAt;
    this.current = current;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonIgnore
  public Optional<String> getCompanyId() {
    if (companyId == null) {
      return Optional.empty();
    }
    return companyId;
  }

  @JsonIgnore
  public Optional<String> getIpAddress() {
    if (ipAddress == null) {
      return Optional.empty();
    }
    return ipAddress;
  }

  @JsonIgnore
  public Optional<String> getUserAgent() {
    if (userAgent == null) {
      return Optional.empty();
    }
    return userAgent;
  }

  @JsonIgnore
  public Optional<String> getLastSeenAt() {
    if (lastSeenAt == null) {
      return Optional.empty();
    }
    return lastSeenAt;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("expiresAt")
  public String getExpiresAt() {
    return expiresAt;
  }

  @JsonProperty("current")
  public boolean getCurrent() {
    return current;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("companyId")
  private Optional<String> _getCompanyId() {
    return companyId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("ipAddress")
  private Optional<String> _getIpAddress() {
    return ipAddress;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("userAgent")
  private Optional<String> _getUserAgent() {
    return userAgent;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("lastSeenAt")
  private Optional<String> _getLastSeenAt() {
    return lastSeenAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1AccountExportResponseSessionsItem && equalTo((PostV1AccountExportResponseSessionsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1AccountExportResponseSessionsItem other) {
    return id.equals(other.id) && companyId.equals(other.companyId) && ipAddress.equals(other.ipAddress) && userAgent.equals(other.userAgent) && lastSeenAt.equals(other.lastSeenAt) && createdAt.equals(other.createdAt) && expiresAt.equals(other.expiresAt) && current == other.current;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.companyId, this.ipAddress, this.userAgent, this.lastSeenAt, this.createdAt, this.expiresAt, this.current);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    CreatedAtStage id(@NotNull String id);

    Builder from(PostV1AccountExportResponseSessionsItem other);
  }

  public interface CreatedAtStage {
    ExpiresAtStage createdAt(@NotNull String createdAt);
  }

  public interface ExpiresAtStage {
    CurrentStage expiresAt(@NotNull String expiresAt);
  }

  public interface CurrentStage {
    _FinalStage current(boolean current);
  }

  public interface _FinalStage {
    PostV1AccountExportResponseSessionsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage companyId(Optional<String> companyId);

    _FinalStage companyId(String companyId);

    _FinalStage companyId(Nullable<String> companyId);

    _FinalStage ipAddress(Optional<String> ipAddress);

    _FinalStage ipAddress(String ipAddress);

    _FinalStage ipAddress(Nullable<String> ipAddress);

    _FinalStage userAgent(Optional<String> userAgent);

    _FinalStage userAgent(String userAgent);

    _FinalStage userAgent(Nullable<String> userAgent);

    _FinalStage lastSeenAt(Optional<String> lastSeenAt);

    _FinalStage lastSeenAt(String lastSeenAt);

    _FinalStage lastSeenAt(Nullable<String> lastSeenAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, CreatedAtStage, ExpiresAtStage, CurrentStage, _FinalStage {
    private String id;

    private String createdAt;

    private String expiresAt;

    private boolean current;

    private Optional<String> lastSeenAt = Optional.empty();

    private Optional<String> userAgent = Optional.empty();

    private Optional<String> ipAddress = Optional.empty();

    private Optional<String> companyId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1AccountExportResponseSessionsItem other) {
      id(other.getId());
      companyId(other.getCompanyId());
      ipAddress(other.getIpAddress());
      userAgent(other.getUserAgent());
      lastSeenAt(other.getLastSeenAt());
      createdAt(other.getCreatedAt());
      expiresAt(other.getExpiresAt());
      current(other.getCurrent());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public CreatedAtStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public ExpiresAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("expiresAt")
    public CurrentStage expiresAt(@NotNull String expiresAt) {
      this.expiresAt = Objects.requireNonNull(expiresAt, "expiresAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("current")
    public _FinalStage current(boolean current) {
      this.current = current;
      return this;
    }

    @java.lang.Override
    public _FinalStage lastSeenAt(Nullable<String> lastSeenAt) {
      if (lastSeenAt.isNull()) {
        this.lastSeenAt = null;
      }
      else if (lastSeenAt.isEmpty()) {
        this.lastSeenAt = Optional.empty();
      }
      else {
        this.lastSeenAt = Optional.of(lastSeenAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage lastSeenAt(String lastSeenAt) {
      this.lastSeenAt = Optional.ofNullable(lastSeenAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lastSeenAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastSeenAt(Optional<String> lastSeenAt) {
      this.lastSeenAt = lastSeenAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage userAgent(Nullable<String> userAgent) {
      if (userAgent.isNull()) {
        this.userAgent = null;
      }
      else if (userAgent.isEmpty()) {
        this.userAgent = Optional.empty();
      }
      else {
        this.userAgent = Optional.of(userAgent.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage userAgent(String userAgent) {
      this.userAgent = Optional.ofNullable(userAgent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "userAgent",
        nulls = Nulls.SKIP
    )
    public _FinalStage userAgent(Optional<String> userAgent) {
      this.userAgent = userAgent;
      return this;
    }

    @java.lang.Override
    public _FinalStage ipAddress(Nullable<String> ipAddress) {
      if (ipAddress.isNull()) {
        this.ipAddress = null;
      }
      else if (ipAddress.isEmpty()) {
        this.ipAddress = Optional.empty();
      }
      else {
        this.ipAddress = Optional.of(ipAddress.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage ipAddress(String ipAddress) {
      this.ipAddress = Optional.ofNullable(ipAddress);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "ipAddress",
        nulls = Nulls.SKIP
    )
    public _FinalStage ipAddress(Optional<String> ipAddress) {
      this.ipAddress = ipAddress;
      return this;
    }

    @java.lang.Override
    public _FinalStage companyId(Nullable<String> companyId) {
      if (companyId.isNull()) {
        this.companyId = null;
      }
      else if (companyId.isEmpty()) {
        this.companyId = Optional.empty();
      }
      else {
        this.companyId = Optional.of(companyId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage companyId(String companyId) {
      this.companyId = Optional.ofNullable(companyId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "companyId",
        nulls = Nulls.SKIP
    )
    public _FinalStage companyId(Optional<String> companyId) {
      this.companyId = companyId;
      return this;
    }

    @java.lang.Override
    public PostV1AccountExportResponseSessionsItem build() {
      return new PostV1AccountExportResponseSessionsItem(id, companyId, ipAddress, userAgent, lastSeenAt, createdAt, expiresAt, current, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
