/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.account.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1AccountMeResponseUser.Builder.class
)
public final class PostV1AccountMeResponseUser {
  private final String id;

  private final String email;

  private final Optional<String> name;

  private final String locale;

  private final String plan;

  private final boolean isSuperAdmin;

  private final Map<String, Object> additionalProperties;

  private PostV1AccountMeResponseUser(String id, String email, Optional<String> name, String locale,
      String plan, boolean isSuperAdmin, Map<String, Object> additionalProperties) {
    this.id = id;
    this.email = email;
    this.name = name;
    this.locale = locale;
    this.plan = plan;
    this.isSuperAdmin = isSuperAdmin;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @JsonIgnore
  public Optional<String> getName() {
    if (name == null) {
      return Optional.empty();
    }
    return name;
  }

  @JsonProperty("locale")
  public String getLocale() {
    return locale;
  }

  @JsonProperty("plan")
  public String getPlan() {
    return plan;
  }

  @JsonProperty("isSuperAdmin")
  public boolean getIsSuperAdmin() {
    return isSuperAdmin;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("name")
  private Optional<String> _getName() {
    return name;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1AccountMeResponseUser && equalTo((PostV1AccountMeResponseUser) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1AccountMeResponseUser other) {
    return id.equals(other.id) && email.equals(other.email) && name.equals(other.name) && locale.equals(other.locale) && plan.equals(other.plan) && isSuperAdmin == other.isSuperAdmin;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.email, this.name, this.locale, this.plan, this.isSuperAdmin);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    EmailStage id(@NotNull String id);

    Builder from(PostV1AccountMeResponseUser other);
  }

  public interface EmailStage {
    LocaleStage email(@NotNull String email);
  }

  public interface LocaleStage {
    PlanStage locale(@NotNull String locale);
  }

  public interface PlanStage {
    IsSuperAdminStage plan(@NotNull String plan);
  }

  public interface IsSuperAdminStage {
    _FinalStage isSuperAdmin(boolean isSuperAdmin);
  }

  public interface _FinalStage {
    PostV1AccountMeResponseUser build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage name(Nullable<String> name);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, EmailStage, LocaleStage, PlanStage, IsSuperAdminStage, _FinalStage {
    private String id;

    private String email;

    private String locale;

    private String plan;

    private boolean isSuperAdmin;

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1AccountMeResponseUser other) {
      id(other.getId());
      email(other.getEmail());
      name(other.getName());
      locale(other.getLocale());
      plan(other.getPlan());
      isSuperAdmin(other.getIsSuperAdmin());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public EmailStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("email")
    public LocaleStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("locale")
    public PlanStage locale(@NotNull String locale) {
      this.locale = Objects.requireNonNull(locale, "locale must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("plan")
    public IsSuperAdminStage plan(@NotNull String plan) {
      this.plan = Objects.requireNonNull(plan, "plan must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("isSuperAdmin")
    public _FinalStage isSuperAdmin(boolean isSuperAdmin) {
      this.isSuperAdmin = isSuperAdmin;
      return this;
    }

    @java.lang.Override
    public _FinalStage name(Nullable<String> name) {
      if (name.isNull()) {
        this.name = null;
      }
      else if (name.isEmpty()) {
        this.name = Optional.empty();
      }
      else {
        this.name = Optional.of(name.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public PostV1AccountMeResponseUser build() {
      return new PostV1AccountMeResponseUser(id, email, name, locale, plan, isSuperAdmin, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
