/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.account.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1AccountCompaniesSelectResponse.Builder.class
)
public final class PostV1AccountCompaniesSelectResponse {
  private final String activeCompanyId;

  private final Map<String, Object> additionalProperties;

  private PostV1AccountCompaniesSelectResponse(String activeCompanyId,
      Map<String, Object> additionalProperties) {
    this.activeCompanyId = activeCompanyId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("activeCompanyId")
  public String getActiveCompanyId() {
    return activeCompanyId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1AccountCompaniesSelectResponse && equalTo((PostV1AccountCompaniesSelectResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1AccountCompaniesSelectResponse other) {
    return activeCompanyId.equals(other.activeCompanyId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.activeCompanyId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ActiveCompanyIdStage builder() {
    return new Builder();
  }

  public interface ActiveCompanyIdStage {
    _FinalStage activeCompanyId(@NotNull String activeCompanyId);

    Builder from(PostV1AccountCompaniesSelectResponse other);
  }

  public interface _FinalStage {
    PostV1AccountCompaniesSelectResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ActiveCompanyIdStage, _FinalStage {
    private String activeCompanyId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1AccountCompaniesSelectResponse other) {
      activeCompanyId(other.getActiveCompanyId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("activeCompanyId")
    public _FinalStage activeCompanyId(@NotNull String activeCompanyId) {
      this.activeCompanyId = Objects.requireNonNull(activeCompanyId, "activeCompanyId must not be null");
      return this;
    }

    @java.lang.Override
    public PostV1AccountCompaniesSelectResponse build() {
      return new PostV1AccountCompaniesSelectResponse(activeCompanyId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
