/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.cash;

import core.ClientOptions;
import core.RequestOptions;
import resources.cash.requests.PostV1CashAdvanceHoldersBalancesRequest;
import resources.cash.requests.PostV1CashBalanceRequest;
import resources.cash.requests.PostV1CashOrdersCreateRequest;
import resources.cash.requests.PostV1CashOrdersGetRequest;
import resources.cash.requests.PostV1CashOrdersListRequest;
import resources.cash.types.PostV1CashAdvanceHoldersBalancesResponse;
import resources.cash.types.PostV1CashBalanceResponse;
import resources.cash.types.PostV1CashOrdersCreateResponse;
import resources.cash.types.PostV1CashOrdersGetResponse;
import resources.cash.types.PostV1CashOrdersListResponse;

public class CashClient {
  protected final ClientOptions clientOptions;

  private final RawCashClient rawClient;

  public CashClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawCashClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawCashClient withRawResponse() {
    return this.rawClient;
  }

  public PostV1CashOrdersCreateResponse postV1CashOrdersCreate(
      PostV1CashOrdersCreateRequest request) {
    return this.rawClient.postV1CashOrdersCreate(request).body();
  }

  public PostV1CashOrdersCreateResponse postV1CashOrdersCreate(
      PostV1CashOrdersCreateRequest request, RequestOptions requestOptions) {
    return this.rawClient.postV1CashOrdersCreate(request, requestOptions).body();
  }

  public PostV1CashOrdersGetResponse postV1CashOrdersGet(PostV1CashOrdersGetRequest request) {
    return this.rawClient.postV1CashOrdersGet(request).body();
  }

  public PostV1CashOrdersGetResponse postV1CashOrdersGet(PostV1CashOrdersGetRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.postV1CashOrdersGet(request, requestOptions).body();
  }

  public PostV1CashOrdersListResponse postV1CashOrdersList() {
    return this.rawClient.postV1CashOrdersList().body();
  }

  public PostV1CashOrdersListResponse postV1CashOrdersList(RequestOptions requestOptions) {
    return this.rawClient.postV1CashOrdersList(requestOptions).body();
  }

  public PostV1CashOrdersListResponse postV1CashOrdersList(PostV1CashOrdersListRequest request) {
    return this.rawClient.postV1CashOrdersList(request).body();
  }

  public PostV1CashOrdersListResponse postV1CashOrdersList(PostV1CashOrdersListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.postV1CashOrdersList(request, requestOptions).body();
  }

  public PostV1CashBalanceResponse postV1CashBalance() {
    return this.rawClient.postV1CashBalance().body();
  }

  public PostV1CashBalanceResponse postV1CashBalance(RequestOptions requestOptions) {
    return this.rawClient.postV1CashBalance(requestOptions).body();
  }

  public PostV1CashBalanceResponse postV1CashBalance(PostV1CashBalanceRequest request) {
    return this.rawClient.postV1CashBalance(request).body();
  }

  public PostV1CashBalanceResponse postV1CashBalance(PostV1CashBalanceRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.postV1CashBalance(request, requestOptions).body();
  }

  public PostV1CashAdvanceHoldersBalancesResponse postV1CashAdvanceHoldersBalances() {
    return this.rawClient.postV1CashAdvanceHoldersBalances().body();
  }

  public PostV1CashAdvanceHoldersBalancesResponse postV1CashAdvanceHoldersBalances(
      RequestOptions requestOptions) {
    return this.rawClient.postV1CashAdvanceHoldersBalances(requestOptions).body();
  }

  public PostV1CashAdvanceHoldersBalancesResponse postV1CashAdvanceHoldersBalances(
      PostV1CashAdvanceHoldersBalancesRequest request) {
    return this.rawClient.postV1CashAdvanceHoldersBalances(request).body();
  }

  public PostV1CashAdvanceHoldersBalancesResponse postV1CashAdvanceHoldersBalances(
      PostV1CashAdvanceHoldersBalancesRequest request, RequestOptions requestOptions) {
    return this.rawClient.postV1CashAdvanceHoldersBalances(request, requestOptions).body();
  }
}
