/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.calendar.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetCalendarResponseSubmissionStatus {
  public static final GetCalendarResponseSubmissionStatus GENERATED = new GetCalendarResponseSubmissionStatus(Value.GENERATED, "generated");

  public static final GetCalendarResponseSubmissionStatus SUBMITTED = new GetCalendarResponseSubmissionStatus(Value.SUBMITTED, "submitted");

  public static final GetCalendarResponseSubmissionStatus ACCEPTED = new GetCalendarResponseSubmissionStatus(Value.ACCEPTED, "accepted");

  public static final GetCalendarResponseSubmissionStatus REJECTED = new GetCalendarResponseSubmissionStatus(Value.REJECTED, "rejected");

  private final Value value;

  private final String string;

  GetCalendarResponseSubmissionStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetCalendarResponseSubmissionStatus && this.string.equals(((GetCalendarResponseSubmissionStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case GENERATED:
        return visitor.visitGenerated();
      case SUBMITTED:
        return visitor.visitSubmitted();
      case ACCEPTED:
        return visitor.visitAccepted();
      case REJECTED:
        return visitor.visitRejected();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetCalendarResponseSubmissionStatus valueOf(String value) {
    switch (value) {
      case "generated":
        return GENERATED;
      case "submitted":
        return SUBMITTED;
      case "accepted":
        return ACCEPTED;
      case "rejected":
        return REJECTED;
      default:
        return new GetCalendarResponseSubmissionStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    GENERATED,

    SUBMITTED,

    ACCEPTED,

    REJECTED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitGenerated();

    T visitSubmitted();

    T visitAccepted();

    T visitRejected();

    T visitUnknown(String unknownType);
  }
}
