/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.calendar.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCalendarResponse.Builder.class
)
public final class ListCalendarResponse {
  private final List<ListCalendarResponseRowsItem> rows;

  private final Map<String, Object> additionalProperties;

  private ListCalendarResponse(List<ListCalendarResponseRowsItem> rows,
      Map<String, Object> additionalProperties) {
    this.rows = rows;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("rows")
  public List<ListCalendarResponseRowsItem> getRows() {
    return rows;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCalendarResponse && equalTo((ListCalendarResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCalendarResponse other) {
    return rows.equals(other.rows);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.rows);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<ListCalendarResponseRowsItem> rows = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCalendarResponse other) {
      rows(other.getRows());
      return this;
    }

    @JsonSetter(
        value = "rows",
        nulls = Nulls.SKIP
    )
    public Builder rows(List<ListCalendarResponseRowsItem> rows) {
      this.rows.clear();
      if (rows != null) {
        this.rows.addAll(rows);
      }
      return this;
    }

    public Builder addRows(ListCalendarResponseRowsItem rows) {
      this.rows.add(rows);
      return this;
    }

    public Builder addAllRows(List<ListCalendarResponseRowsItem> rows) {
      if (rows != null) {
        this.rows.addAll(rows);
      }
      return this;
    }

    public ListCalendarResponse build() {
      return new ListCalendarResponse(rows, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
