/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import com.nordlet.api.resources.declarations.types.DeReturnsGenerateDeclarationsRequestRuleKey;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DeReturnsGenerateDeclarationsRequest.Builder.class
)
public final class DeReturnsGenerateDeclarationsRequest {
  private final DeReturnsGenerateDeclarationsRequestRuleKey ruleKey;

  private final String period;

  private final Map<String, Object> additionalProperties;

  private DeReturnsGenerateDeclarationsRequest(DeReturnsGenerateDeclarationsRequestRuleKey ruleKey,
      String period, Map<String, Object> additionalProperties) {
    this.ruleKey = ruleKey;
    this.period = period;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("ruleKey")
  public DeReturnsGenerateDeclarationsRequestRuleKey getRuleKey() {
    return ruleKey;
  }

  @JsonProperty("period")
  public String getPeriod() {
    return period;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DeReturnsGenerateDeclarationsRequest && equalTo((DeReturnsGenerateDeclarationsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DeReturnsGenerateDeclarationsRequest other) {
    return ruleKey.equals(other.ruleKey) && period.equals(other.period);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.ruleKey, this.period);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RuleKeyStage builder() {
    return new Builder();
  }

  public interface RuleKeyStage {
    PeriodStage ruleKey(@NotNull DeReturnsGenerateDeclarationsRequestRuleKey ruleKey);

    Builder from(DeReturnsGenerateDeclarationsRequest other);
  }

  public interface PeriodStage {
    _FinalStage period(@NotNull String period);
  }

  public interface _FinalStage {
    DeReturnsGenerateDeclarationsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RuleKeyStage, PeriodStage, _FinalStage {
    private DeReturnsGenerateDeclarationsRequestRuleKey ruleKey;

    private String period;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DeReturnsGenerateDeclarationsRequest other) {
      ruleKey(other.getRuleKey());
      period(other.getPeriod());
      return this;
    }

    @java.lang.Override
    @JsonSetter("ruleKey")
    public PeriodStage ruleKey(@NotNull DeReturnsGenerateDeclarationsRequestRuleKey ruleKey) {
      this.ruleKey = Objects.requireNonNull(ruleKey, "ruleKey must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("period")
    public _FinalStage period(@NotNull String period) {
      this.period = Objects.requireNonNull(period, "period must not be null");
      return this;
    }

    @java.lang.Override
    public DeReturnsGenerateDeclarationsRequest build() {
      return new DeReturnsGenerateDeclarationsRequest(ruleKey, period, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
