/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import com.nordlet.api.resources.declarations.types.PlIntrastatGenerateDeclarationsRequestFlow;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PlIntrastatGenerateDeclarationsRequest.Builder.class
)
public final class PlIntrastatGenerateDeclarationsRequest {
  private final long year;

  private final long month;

  private final PlIntrastatGenerateDeclarationsRequestFlow flow;

  private final Optional<String> transactionNature;

  private final Map<String, Object> additionalProperties;

  private PlIntrastatGenerateDeclarationsRequest(long year, long month,
      PlIntrastatGenerateDeclarationsRequestFlow flow, Optional<String> transactionNature,
      Map<String, Object> additionalProperties) {
    this.year = year;
    this.month = month;
    this.flow = flow;
    this.transactionNature = transactionNature;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("year")
  public long getYear() {
    return year;
  }

  @JsonProperty("month")
  public long getMonth() {
    return month;
  }

  @JsonProperty("flow")
  public PlIntrastatGenerateDeclarationsRequestFlow getFlow() {
    return flow;
  }

  @JsonProperty("transactionNature")
  public Optional<String> getTransactionNature() {
    return transactionNature;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PlIntrastatGenerateDeclarationsRequest && equalTo((PlIntrastatGenerateDeclarationsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PlIntrastatGenerateDeclarationsRequest other) {
    return year == other.year && month == other.month && flow.equals(other.flow) && transactionNature.equals(other.transactionNature);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.year, this.month, this.flow, this.transactionNature);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static YearStage builder() {
    return new Builder();
  }

  public interface YearStage {
    MonthStage year(long year);

    Builder from(PlIntrastatGenerateDeclarationsRequest other);
  }

  public interface MonthStage {
    FlowStage month(long month);
  }

  public interface FlowStage {
    _FinalStage flow(@NotNull PlIntrastatGenerateDeclarationsRequestFlow flow);
  }

  public interface _FinalStage {
    PlIntrastatGenerateDeclarationsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage transactionNature(Optional<String> transactionNature);

    _FinalStage transactionNature(String transactionNature);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements YearStage, MonthStage, FlowStage, _FinalStage {
    private long year;

    private long month;

    private PlIntrastatGenerateDeclarationsRequestFlow flow;

    private Optional<String> transactionNature = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PlIntrastatGenerateDeclarationsRequest other) {
      year(other.getYear());
      month(other.getMonth());
      flow(other.getFlow());
      transactionNature(other.getTransactionNature());
      return this;
    }

    @java.lang.Override
    @JsonSetter("year")
    public MonthStage year(long year) {
      this.year = year;
      return this;
    }

    @java.lang.Override
    @JsonSetter("month")
    public FlowStage month(long month) {
      this.month = month;
      return this;
    }

    @java.lang.Override
    @JsonSetter("flow")
    public _FinalStage flow(@NotNull PlIntrastatGenerateDeclarationsRequestFlow flow) {
      this.flow = Objects.requireNonNull(flow, "flow must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage transactionNature(String transactionNature) {
      this.transactionNature = Optional.ofNullable(transactionNature);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "transactionNature",
        nulls = Nulls.SKIP
    )
    public _FinalStage transactionNature(Optional<String> transactionNature) {
      this.transactionNature = transactionNature;
      return this;
    }

    @java.lang.Override
    public PlIntrastatGenerateDeclarationsRequest build() {
      return new PlIntrastatGenerateDeclarationsRequest(year, month, flow, transactionNature, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
