/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1DeclarationsEuDistanceSalesThresholdGetRequest.Builder.class
)
public final class PostV1DeclarationsEuDistanceSalesThresholdGetRequest {
  private final Optional<String> date;

  private final Map<String, Object> additionalProperties;

  private PostV1DeclarationsEuDistanceSalesThresholdGetRequest(Optional<String> date,
      Map<String, Object> additionalProperties) {
    this.date = date;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("date")
  public Optional<String> getDate() {
    return date;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1DeclarationsEuDistanceSalesThresholdGetRequest && equalTo((PostV1DeclarationsEuDistanceSalesThresholdGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1DeclarationsEuDistanceSalesThresholdGetRequest other) {
    return date.equals(other.date);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.date);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> date = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PostV1DeclarationsEuDistanceSalesThresholdGetRequest other) {
      date(other.getDate());
      return this;
    }

    @JsonSetter(
        value = "date",
        nulls = Nulls.SKIP
    )
    public Builder date(Optional<String> date) {
      this.date = date;
      return this;
    }

    public Builder date(String date) {
      this.date = Optional.ofNullable(date);
      return this;
    }

    public PostV1DeclarationsEuDistanceSalesThresholdGetRequest build() {
      return new PostV1DeclarationsEuDistanceSalesThresholdGetRequest(date, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
