/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RoEtransportStatusDeclarationsRequest.Builder.class
)
public final class RoEtransportStatusDeclarationsRequest {
  private final String reference;

  private final Map<String, Object> additionalProperties;

  private RoEtransportStatusDeclarationsRequest(String reference,
      Map<String, Object> additionalProperties) {
    this.reference = reference;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("reference")
  public String getReference() {
    return reference;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RoEtransportStatusDeclarationsRequest && equalTo((RoEtransportStatusDeclarationsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RoEtransportStatusDeclarationsRequest other) {
    return reference.equals(other.reference);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.reference);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ReferenceStage builder() {
    return new Builder();
  }

  public interface ReferenceStage {
    _FinalStage reference(@NotNull String reference);

    Builder from(RoEtransportStatusDeclarationsRequest other);
  }

  public interface _FinalStage {
    RoEtransportStatusDeclarationsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ReferenceStage, _FinalStage {
    private String reference;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RoEtransportStatusDeclarationsRequest other) {
      reference(other.getReference());
      return this;
    }

    @java.lang.Override
    @JsonSetter("reference")
    public _FinalStage reference(@NotNull String reference) {
      this.reference = Objects.requireNonNull(reference, "reference must not be null");
      return this;
    }

    @java.lang.Override
    public RoEtransportStatusDeclarationsRequest build() {
      return new RoEtransportStatusDeclarationsRequest(reference, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
