/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.transport.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.transport.types.PostV1TransportWaybillsCreateRequestLinesItem;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1TransportWaybillsCreateRequest.Builder.class
)
public final class PostV1TransportWaybillsCreateRequest {
  private final String consigneePartnerId;

  private final Optional<String> transporterPartnerId;

  private final Optional<String> documentDate;

  private final OffsetDateTime dispatchAt;

  private final Optional<OffsetDateTime> estimatedArrivalAt;

  private final Optional<String> vehiclePlate;

  private final Optional<String> trailerPlate;

  private final Optional<String> driverName;

  private final Optional<String> driverSurname;

  private final Optional<String> loadWarehouseId;

  private final String loadAddress;

  private final String unloadAddress;

  private final Optional<String> valueEur;

  private final Optional<String> saleInvoiceId;

  private final Optional<String> notes;

  private final Optional<String> series;

  private final Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> lines;

  private final Map<String, Object> additionalProperties;

  private PostV1TransportWaybillsCreateRequest(String consigneePartnerId,
      Optional<String> transporterPartnerId, Optional<String> documentDate,
      OffsetDateTime dispatchAt, Optional<OffsetDateTime> estimatedArrivalAt,
      Optional<String> vehiclePlate, Optional<String> trailerPlate, Optional<String> driverName,
      Optional<String> driverSurname, Optional<String> loadWarehouseId, String loadAddress,
      String unloadAddress, Optional<String> valueEur, Optional<String> saleInvoiceId,
      Optional<String> notes, Optional<String> series,
      Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> lines,
      Map<String, Object> additionalProperties) {
    this.consigneePartnerId = consigneePartnerId;
    this.transporterPartnerId = transporterPartnerId;
    this.documentDate = documentDate;
    this.dispatchAt = dispatchAt;
    this.estimatedArrivalAt = estimatedArrivalAt;
    this.vehiclePlate = vehiclePlate;
    this.trailerPlate = trailerPlate;
    this.driverName = driverName;
    this.driverSurname = driverSurname;
    this.loadWarehouseId = loadWarehouseId;
    this.loadAddress = loadAddress;
    this.unloadAddress = unloadAddress;
    this.valueEur = valueEur;
    this.saleInvoiceId = saleInvoiceId;
    this.notes = notes;
    this.series = series;
    this.lines = lines;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("consigneePartnerId")
  public String getConsigneePartnerId() {
    return consigneePartnerId;
  }

  @JsonProperty("transporterPartnerId")
  public Optional<String> getTransporterPartnerId() {
    return transporterPartnerId;
  }

  @JsonProperty("documentDate")
  public Optional<String> getDocumentDate() {
    return documentDate;
  }

  @JsonProperty("dispatchAt")
  public OffsetDateTime getDispatchAt() {
    return dispatchAt;
  }

  @JsonProperty("estimatedArrivalAt")
  public Optional<OffsetDateTime> getEstimatedArrivalAt() {
    return estimatedArrivalAt;
  }

  @JsonProperty("vehiclePlate")
  public Optional<String> getVehiclePlate() {
    return vehiclePlate;
  }

  @JsonProperty("trailerPlate")
  public Optional<String> getTrailerPlate() {
    return trailerPlate;
  }

  @JsonProperty("driverName")
  public Optional<String> getDriverName() {
    return driverName;
  }

  @JsonProperty("driverSurname")
  public Optional<String> getDriverSurname() {
    return driverSurname;
  }

  @JsonProperty("loadWarehouseId")
  public Optional<String> getLoadWarehouseId() {
    return loadWarehouseId;
  }

  @JsonProperty("loadAddress")
  public String getLoadAddress() {
    return loadAddress;
  }

  @JsonProperty("unloadAddress")
  public String getUnloadAddress() {
    return unloadAddress;
  }

  @JsonProperty("valueEur")
  public Optional<String> getValueEur() {
    return valueEur;
  }

  @JsonProperty("saleInvoiceId")
  public Optional<String> getSaleInvoiceId() {
    return saleInvoiceId;
  }

  @JsonProperty("notes")
  public Optional<String> getNotes() {
    return notes;
  }

  @JsonProperty("series")
  public Optional<String> getSeries() {
    return series;
  }

  @JsonProperty("lines")
  public Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> getLines() {
    return lines;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1TransportWaybillsCreateRequest && equalTo((PostV1TransportWaybillsCreateRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1TransportWaybillsCreateRequest other) {
    return consigneePartnerId.equals(other.consigneePartnerId) && transporterPartnerId.equals(other.transporterPartnerId) && documentDate.equals(other.documentDate) && dispatchAt.equals(other.dispatchAt) && estimatedArrivalAt.equals(other.estimatedArrivalAt) && vehiclePlate.equals(other.vehiclePlate) && trailerPlate.equals(other.trailerPlate) && driverName.equals(other.driverName) && driverSurname.equals(other.driverSurname) && loadWarehouseId.equals(other.loadWarehouseId) && loadAddress.equals(other.loadAddress) && unloadAddress.equals(other.unloadAddress) && valueEur.equals(other.valueEur) && saleInvoiceId.equals(other.saleInvoiceId) && notes.equals(other.notes) && series.equals(other.series) && lines.equals(other.lines);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.consigneePartnerId, this.transporterPartnerId, this.documentDate, this.dispatchAt, this.estimatedArrivalAt, this.vehiclePlate, this.trailerPlate, this.driverName, this.driverSurname, this.loadWarehouseId, this.loadAddress, this.unloadAddress, this.valueEur, this.saleInvoiceId, this.notes, this.series, this.lines);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ConsigneePartnerIdStage builder() {
    return new Builder();
  }

  public interface ConsigneePartnerIdStage {
    DispatchAtStage consigneePartnerId(@NotNull String consigneePartnerId);

    Builder from(PostV1TransportWaybillsCreateRequest other);
  }

  public interface DispatchAtStage {
    LoadAddressStage dispatchAt(@NotNull OffsetDateTime dispatchAt);
  }

  public interface LoadAddressStage {
    UnloadAddressStage loadAddress(@NotNull String loadAddress);
  }

  public interface UnloadAddressStage {
    _FinalStage unloadAddress(@NotNull String unloadAddress);
  }

  public interface _FinalStage {
    PostV1TransportWaybillsCreateRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage transporterPartnerId(Optional<String> transporterPartnerId);

    _FinalStage transporterPartnerId(String transporterPartnerId);

    _FinalStage documentDate(Optional<String> documentDate);

    _FinalStage documentDate(String documentDate);

    _FinalStage estimatedArrivalAt(Optional<OffsetDateTime> estimatedArrivalAt);

    _FinalStage estimatedArrivalAt(OffsetDateTime estimatedArrivalAt);

    _FinalStage vehiclePlate(Optional<String> vehiclePlate);

    _FinalStage vehiclePlate(String vehiclePlate);

    _FinalStage trailerPlate(Optional<String> trailerPlate);

    _FinalStage trailerPlate(String trailerPlate);

    _FinalStage driverName(Optional<String> driverName);

    _FinalStage driverName(String driverName);

    _FinalStage driverSurname(Optional<String> driverSurname);

    _FinalStage driverSurname(String driverSurname);

    _FinalStage loadWarehouseId(Optional<String> loadWarehouseId);

    _FinalStage loadWarehouseId(String loadWarehouseId);

    _FinalStage valueEur(Optional<String> valueEur);

    _FinalStage valueEur(String valueEur);

    _FinalStage saleInvoiceId(Optional<String> saleInvoiceId);

    _FinalStage saleInvoiceId(String saleInvoiceId);

    _FinalStage notes(Optional<String> notes);

    _FinalStage notes(String notes);

    _FinalStage series(Optional<String> series);

    _FinalStage series(String series);

    _FinalStage lines(Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> lines);

    _FinalStage lines(List<PostV1TransportWaybillsCreateRequestLinesItem> lines);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ConsigneePartnerIdStage, DispatchAtStage, LoadAddressStage, UnloadAddressStage, _FinalStage {
    private String consigneePartnerId;

    private OffsetDateTime dispatchAt;

    private String loadAddress;

    private String unloadAddress;

    private Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> lines = Optional.empty();

    private Optional<String> series = Optional.empty();

    private Optional<String> notes = Optional.empty();

    private Optional<String> saleInvoiceId = Optional.empty();

    private Optional<String> valueEur = Optional.empty();

    private Optional<String> loadWarehouseId = Optional.empty();

    private Optional<String> driverSurname = Optional.empty();

    private Optional<String> driverName = Optional.empty();

    private Optional<String> trailerPlate = Optional.empty();

    private Optional<String> vehiclePlate = Optional.empty();

    private Optional<OffsetDateTime> estimatedArrivalAt = Optional.empty();

    private Optional<String> documentDate = Optional.empty();

    private Optional<String> transporterPartnerId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1TransportWaybillsCreateRequest other) {
      consigneePartnerId(other.getConsigneePartnerId());
      transporterPartnerId(other.getTransporterPartnerId());
      documentDate(other.getDocumentDate());
      dispatchAt(other.getDispatchAt());
      estimatedArrivalAt(other.getEstimatedArrivalAt());
      vehiclePlate(other.getVehiclePlate());
      trailerPlate(other.getTrailerPlate());
      driverName(other.getDriverName());
      driverSurname(other.getDriverSurname());
      loadWarehouseId(other.getLoadWarehouseId());
      loadAddress(other.getLoadAddress());
      unloadAddress(other.getUnloadAddress());
      valueEur(other.getValueEur());
      saleInvoiceId(other.getSaleInvoiceId());
      notes(other.getNotes());
      series(other.getSeries());
      lines(other.getLines());
      return this;
    }

    @java.lang.Override
    @JsonSetter("consigneePartnerId")
    public DispatchAtStage consigneePartnerId(@NotNull String consigneePartnerId) {
      this.consigneePartnerId = Objects.requireNonNull(consigneePartnerId, "consigneePartnerId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("dispatchAt")
    public LoadAddressStage dispatchAt(@NotNull OffsetDateTime dispatchAt) {
      this.dispatchAt = Objects.requireNonNull(dispatchAt, "dispatchAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("loadAddress")
    public UnloadAddressStage loadAddress(@NotNull String loadAddress) {
      this.loadAddress = Objects.requireNonNull(loadAddress, "loadAddress must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("unloadAddress")
    public _FinalStage unloadAddress(@NotNull String unloadAddress) {
      this.unloadAddress = Objects.requireNonNull(unloadAddress, "unloadAddress must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage lines(List<PostV1TransportWaybillsCreateRequestLinesItem> lines) {
      this.lines = Optional.ofNullable(lines);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lines",
        nulls = Nulls.SKIP
    )
    public _FinalStage lines(Optional<List<PostV1TransportWaybillsCreateRequestLinesItem>> lines) {
      this.lines = lines;
      return this;
    }

    @java.lang.Override
    public _FinalStage series(String series) {
      this.series = Optional.ofNullable(series);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "series",
        nulls = Nulls.SKIP
    )
    public _FinalStage series(Optional<String> series) {
      this.series = series;
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(String notes) {
      this.notes = Optional.ofNullable(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(Optional<String> notes) {
      this.notes = notes;
      return this;
    }

    @java.lang.Override
    public _FinalStage saleInvoiceId(String saleInvoiceId) {
      this.saleInvoiceId = Optional.ofNullable(saleInvoiceId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "saleInvoiceId",
        nulls = Nulls.SKIP
    )
    public _FinalStage saleInvoiceId(Optional<String> saleInvoiceId) {
      this.saleInvoiceId = saleInvoiceId;
      return this;
    }

    @java.lang.Override
    public _FinalStage valueEur(String valueEur) {
      this.valueEur = Optional.ofNullable(valueEur);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "valueEur",
        nulls = Nulls.SKIP
    )
    public _FinalStage valueEur(Optional<String> valueEur) {
      this.valueEur = valueEur;
      return this;
    }

    @java.lang.Override
    public _FinalStage loadWarehouseId(String loadWarehouseId) {
      this.loadWarehouseId = Optional.ofNullable(loadWarehouseId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "loadWarehouseId",
        nulls = Nulls.SKIP
    )
    public _FinalStage loadWarehouseId(Optional<String> loadWarehouseId) {
      this.loadWarehouseId = loadWarehouseId;
      return this;
    }

    @java.lang.Override
    public _FinalStage driverSurname(String driverSurname) {
      this.driverSurname = Optional.ofNullable(driverSurname);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "driverSurname",
        nulls = Nulls.SKIP
    )
    public _FinalStage driverSurname(Optional<String> driverSurname) {
      this.driverSurname = driverSurname;
      return this;
    }

    @java.lang.Override
    public _FinalStage driverName(String driverName) {
      this.driverName = Optional.ofNullable(driverName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "driverName",
        nulls = Nulls.SKIP
    )
    public _FinalStage driverName(Optional<String> driverName) {
      this.driverName = driverName;
      return this;
    }

    @java.lang.Override
    public _FinalStage trailerPlate(String trailerPlate) {
      this.trailerPlate = Optional.ofNullable(trailerPlate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "trailerPlate",
        nulls = Nulls.SKIP
    )
    public _FinalStage trailerPlate(Optional<String> trailerPlate) {
      this.trailerPlate = trailerPlate;
      return this;
    }

    @java.lang.Override
    public _FinalStage vehiclePlate(String vehiclePlate) {
      this.vehiclePlate = Optional.ofNullable(vehiclePlate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "vehiclePlate",
        nulls = Nulls.SKIP
    )
    public _FinalStage vehiclePlate(Optional<String> vehiclePlate) {
      this.vehiclePlate = vehiclePlate;
      return this;
    }

    @java.lang.Override
    public _FinalStage estimatedArrivalAt(OffsetDateTime estimatedArrivalAt) {
      this.estimatedArrivalAt = Optional.ofNullable(estimatedArrivalAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "estimatedArrivalAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage estimatedArrivalAt(Optional<OffsetDateTime> estimatedArrivalAt) {
      this.estimatedArrivalAt = estimatedArrivalAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage documentDate(String documentDate) {
      this.documentDate = Optional.ofNullable(documentDate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "documentDate",
        nulls = Nulls.SKIP
    )
    public _FinalStage documentDate(Optional<String> documentDate) {
      this.documentDate = documentDate;
      return this;
    }

    @java.lang.Override
    public _FinalStage transporterPartnerId(String transporterPartnerId) {
      this.transporterPartnerId = Optional.ofNullable(transporterPartnerId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "transporterPartnerId",
        nulls = Nulls.SKIP
    )
    public _FinalStage transporterPartnerId(Optional<String> transporterPartnerId) {
      this.transporterPartnerId = transporterPartnerId;
      return this;
    }

    @java.lang.Override
    public PostV1TransportWaybillsCreateRequest build() {
      return new PostV1TransportWaybillsCreateRequest(consigneePartnerId, transporterPartnerId, documentDate, dispatchAt, estimatedArrivalAt, vehiclePlate, trailerPlate, driverName, driverSurname, loadWarehouseId, loadAddress, unloadAddress, valueEur, saleInvoiceId, notes, series, lines, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
