/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.purchases.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import com.nordlet.api.resources.purchases.types.ReceiptsCreatePurchasesRequestLinesItem;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ReceiptsCreatePurchasesRequest.Builder.class
)
public final class ReceiptsCreatePurchasesRequest {
  private final String orderId;

  private final String receiptDate;

  private final Optional<String> warehouseId;

  private final Optional<String> notes;

  private final List<ReceiptsCreatePurchasesRequestLinesItem> lines;

  private final Map<String, Object> additionalProperties;

  private ReceiptsCreatePurchasesRequest(String orderId, String receiptDate,
      Optional<String> warehouseId, Optional<String> notes,
      List<ReceiptsCreatePurchasesRequestLinesItem> lines,
      Map<String, Object> additionalProperties) {
    this.orderId = orderId;
    this.receiptDate = receiptDate;
    this.warehouseId = warehouseId;
    this.notes = notes;
    this.lines = lines;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("orderId")
  public String getOrderId() {
    return orderId;
  }

  @JsonProperty("receiptDate")
  public String getReceiptDate() {
    return receiptDate;
  }

  @JsonProperty("warehouseId")
  public Optional<String> getWarehouseId() {
    return warehouseId;
  }

  @JsonProperty("notes")
  public Optional<String> getNotes() {
    return notes;
  }

  @JsonProperty("lines")
  public List<ReceiptsCreatePurchasesRequestLinesItem> getLines() {
    return lines;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ReceiptsCreatePurchasesRequest && equalTo((ReceiptsCreatePurchasesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ReceiptsCreatePurchasesRequest other) {
    return orderId.equals(other.orderId) && receiptDate.equals(other.receiptDate) && warehouseId.equals(other.warehouseId) && notes.equals(other.notes) && lines.equals(other.lines);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.orderId, this.receiptDate, this.warehouseId, this.notes, this.lines);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OrderIdStage builder() {
    return new Builder();
  }

  public interface OrderIdStage {
    ReceiptDateStage orderId(@NotNull String orderId);

    Builder from(ReceiptsCreatePurchasesRequest other);
  }

  public interface ReceiptDateStage {
    _FinalStage receiptDate(@NotNull String receiptDate);
  }

  public interface _FinalStage {
    ReceiptsCreatePurchasesRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage warehouseId(Optional<String> warehouseId);

    _FinalStage warehouseId(String warehouseId);

    _FinalStage notes(Optional<String> notes);

    _FinalStage notes(String notes);

    _FinalStage lines(List<ReceiptsCreatePurchasesRequestLinesItem> lines);

    _FinalStage addLines(ReceiptsCreatePurchasesRequestLinesItem lines);

    _FinalStage addAllLines(List<ReceiptsCreatePurchasesRequestLinesItem> lines);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OrderIdStage, ReceiptDateStage, _FinalStage {
    private String orderId;

    private String receiptDate;

    private List<ReceiptsCreatePurchasesRequestLinesItem> lines = new ArrayList<>();

    private Optional<String> notes = Optional.empty();

    private Optional<String> warehouseId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ReceiptsCreatePurchasesRequest other) {
      orderId(other.getOrderId());
      receiptDate(other.getReceiptDate());
      warehouseId(other.getWarehouseId());
      notes(other.getNotes());
      lines(other.getLines());
      return this;
    }

    @java.lang.Override
    @JsonSetter("orderId")
    public ReceiptDateStage orderId(@NotNull String orderId) {
      this.orderId = Objects.requireNonNull(orderId, "orderId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("receiptDate")
    public _FinalStage receiptDate(@NotNull String receiptDate) {
      this.receiptDate = Objects.requireNonNull(receiptDate, "receiptDate must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLines(List<ReceiptsCreatePurchasesRequestLinesItem> lines) {
      if (lines != null) {
        this.lines.addAll(lines);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addLines(ReceiptsCreatePurchasesRequestLinesItem lines) {
      this.lines.add(lines);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lines",
        nulls = Nulls.SKIP
    )
    public _FinalStage lines(List<ReceiptsCreatePurchasesRequestLinesItem> lines) {
      this.lines.clear();
      if (lines != null) {
        this.lines.addAll(lines);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage notes(String notes) {
      this.notes = Optional.ofNullable(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(Optional<String> notes) {
      this.notes = notes;
      return this;
    }

    @java.lang.Override
    public _FinalStage warehouseId(String warehouseId) {
      this.warehouseId = Optional.ofNullable(warehouseId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warehouseId",
        nulls = Nulls.SKIP
    )
    public _FinalStage warehouseId(Optional<String> warehouseId) {
      this.warehouseId = warehouseId;
      return this;
    }

    @java.lang.Override
    public ReceiptsCreatePurchasesRequest build() {
      return new ReceiptsCreatePurchasesRequest(orderId, receiptDate, warehouseId, notes, lines, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
