/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.public_;

import com.nordlet.api.core.ClientOptions;
import com.nordlet.api.core.RequestOptions;
import com.nordlet.api.resources.public_.requests.IntegrationRequestsPublicRequest;
import com.nordlet.api.resources.public_.requests.PayPublicRequest;
import com.nordlet.api.resources.public_.types.IntegrationRequestsPublicResponse;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;

public class AsyncPublicClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawPublicClient rawClient;

  public AsyncPublicClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawPublicClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawPublicClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<IntegrationRequestsPublicResponse> integrationRequests(
      IntegrationRequestsPublicRequest request) {
    return this.rawClient.integrationRequests(request).thenApply(response -> response.body());
  }

  public CompletableFuture<IntegrationRequestsPublicResponse> integrationRequests(
      IntegrationRequestsPublicRequest request, RequestOptions requestOptions) {
    return this.rawClient.integrationRequests(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> pay(String token) {
    return this.rawClient.pay(token).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> pay(String token, RequestOptions requestOptions) {
    return this.rawClient.pay(token, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> pay(String token, PayPublicRequest request) {
    return this.rawClient.pay(token, request).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> pay(String token, PayPublicRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.pay(token, request, requestOptions).thenApply(response -> response.body());
  }
}
