/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.bank.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FeedsConnectionsStartBankResponse.Builder.class
)
public final class FeedsConnectionsStartBankResponse {
  private final String connectionId;

  private final String reference;

  private final String url;

  private final OffsetDateTime expiresAt;

  private final Map<String, Object> additionalProperties;

  private FeedsConnectionsStartBankResponse(String connectionId, String reference, String url,
      OffsetDateTime expiresAt, Map<String, Object> additionalProperties) {
    this.connectionId = connectionId;
    this.reference = reference;
    this.url = url;
    this.expiresAt = expiresAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("connectionId")
  public String getConnectionId() {
    return connectionId;
  }

  @JsonProperty("reference")
  public String getReference() {
    return reference;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @JsonProperty("expiresAt")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FeedsConnectionsStartBankResponse && equalTo((FeedsConnectionsStartBankResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FeedsConnectionsStartBankResponse other) {
    return connectionId.equals(other.connectionId) && reference.equals(other.reference) && url.equals(other.url) && expiresAt.equals(other.expiresAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.connectionId, this.reference, this.url, this.expiresAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ConnectionIdStage builder() {
    return new Builder();
  }

  public interface ConnectionIdStage {
    ReferenceStage connectionId(@NotNull String connectionId);

    Builder from(FeedsConnectionsStartBankResponse other);
  }

  public interface ReferenceStage {
    UrlStage reference(@NotNull String reference);
  }

  public interface UrlStage {
    ExpiresAtStage url(@NotNull String url);
  }

  public interface ExpiresAtStage {
    _FinalStage expiresAt(@NotNull OffsetDateTime expiresAt);
  }

  public interface _FinalStage {
    FeedsConnectionsStartBankResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ConnectionIdStage, ReferenceStage, UrlStage, ExpiresAtStage, _FinalStage {
    private String connectionId;

    private String reference;

    private String url;

    private OffsetDateTime expiresAt;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(FeedsConnectionsStartBankResponse other) {
      connectionId(other.getConnectionId());
      reference(other.getReference());
      url(other.getUrl());
      expiresAt(other.getExpiresAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("connectionId")
    public ReferenceStage connectionId(@NotNull String connectionId) {
      this.connectionId = Objects.requireNonNull(connectionId, "connectionId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("reference")
    public UrlStage reference(@NotNull String reference) {
      this.reference = Objects.requireNonNull(reference, "reference must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public ExpiresAtStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("expiresAt")
    public _FinalStage expiresAt(@NotNull OffsetDateTime expiresAt) {
      this.expiresAt = Objects.requireNonNull(expiresAt, "expiresAt must not be null");
      return this;
    }

    @java.lang.Override
    public FeedsConnectionsStartBankResponse build() {
      return new FeedsConnectionsStartBankResponse(connectionId, reference, url, expiresAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
