/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.files;

import com.nordlet.api.core.ClientOptions;
import com.nordlet.api.core.RequestOptions;
import com.nordlet.api.resources.files.requests.DeleteFilesRequest;
import com.nordlet.api.resources.files.requests.GetFilesRequest;
import com.nordlet.api.resources.files.requests.ListFilesRequest;
import com.nordlet.api.resources.files.requests.UploadFilesRequest;
import com.nordlet.api.resources.files.types.DeleteFilesResponse;
import com.nordlet.api.resources.files.types.GetFilesResponse;
import com.nordlet.api.resources.files.types.ListFilesResponse;
import com.nordlet.api.resources.files.types.UploadFilesResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncFilesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawFilesClient rawClient;

  public AsyncFilesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawFilesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawFilesClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<UploadFilesResponse> upload(UploadFilesRequest request) {
    return this.rawClient.upload(request).thenApply(response -> response.body());
  }

  public CompletableFuture<UploadFilesResponse> upload(UploadFilesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.upload(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<GetFilesResponse> get(GetFilesRequest request) {
    return this.rawClient.get(request).thenApply(response -> response.body());
  }

  public CompletableFuture<GetFilesResponse> get(GetFilesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<ListFilesResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  public CompletableFuture<ListFilesResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<ListFilesResponse> list(ListFilesRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  public CompletableFuture<ListFilesResponse> list(ListFilesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<DeleteFilesResponse> delete(DeleteFilesRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  public CompletableFuture<DeleteFilesResponse> delete(DeleteFilesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }
}
