/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.reports.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1ReportsStockAgingResponseRowsItem.Builder.class
)
public final class PostV1ReportsStockAgingResponseRowsItem {
  private final String itemId;

  private final String itemName;

  private final String warehouseId;

  private final String d0To30Qty;

  private final String d0To30Value;

  private final String d31To60Qty;

  private final String d31To60Value;

  private final String d61To90Qty;

  private final String d61To90Value;

  private final String over90Qty;

  private final String over90Value;

  private final String totalQty;

  private final String totalValue;

  private final Map<String, Object> additionalProperties;

  private PostV1ReportsStockAgingResponseRowsItem(String itemId, String itemName,
      String warehouseId, String d0To30Qty, String d0To30Value, String d31To60Qty,
      String d31To60Value, String d61To90Qty, String d61To90Value, String over90Qty,
      String over90Value, String totalQty, String totalValue,
      Map<String, Object> additionalProperties) {
    this.itemId = itemId;
    this.itemName = itemName;
    this.warehouseId = warehouseId;
    this.d0To30Qty = d0To30Qty;
    this.d0To30Value = d0To30Value;
    this.d31To60Qty = d31To60Qty;
    this.d31To60Value = d31To60Value;
    this.d61To90Qty = d61To90Qty;
    this.d61To90Value = d61To90Value;
    this.over90Qty = over90Qty;
    this.over90Value = over90Value;
    this.totalQty = totalQty;
    this.totalValue = totalValue;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("itemId")
  public String getItemId() {
    return itemId;
  }

  @JsonProperty("itemName")
  public String getItemName() {
    return itemName;
  }

  @JsonProperty("warehouseId")
  public String getWarehouseId() {
    return warehouseId;
  }

  @JsonProperty("d0to30Qty")
  public String getD0To30Qty() {
    return d0To30Qty;
  }

  @JsonProperty("d0to30Value")
  public String getD0To30Value() {
    return d0To30Value;
  }

  @JsonProperty("d31to60Qty")
  public String getD31To60Qty() {
    return d31To60Qty;
  }

  @JsonProperty("d31to60Value")
  public String getD31To60Value() {
    return d31To60Value;
  }

  @JsonProperty("d61to90Qty")
  public String getD61To90Qty() {
    return d61To90Qty;
  }

  @JsonProperty("d61to90Value")
  public String getD61To90Value() {
    return d61To90Value;
  }

  @JsonProperty("over90Qty")
  public String getOver90Qty() {
    return over90Qty;
  }

  @JsonProperty("over90Value")
  public String getOver90Value() {
    return over90Value;
  }

  @JsonProperty("totalQty")
  public String getTotalQty() {
    return totalQty;
  }

  @JsonProperty("totalValue")
  public String getTotalValue() {
    return totalValue;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1ReportsStockAgingResponseRowsItem && equalTo((PostV1ReportsStockAgingResponseRowsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1ReportsStockAgingResponseRowsItem other) {
    return itemId.equals(other.itemId) && itemName.equals(other.itemName) && warehouseId.equals(other.warehouseId) && d0To30Qty.equals(other.d0To30Qty) && d0To30Value.equals(other.d0To30Value) && d31To60Qty.equals(other.d31To60Qty) && d31To60Value.equals(other.d31To60Value) && d61To90Qty.equals(other.d61To90Qty) && d61To90Value.equals(other.d61To90Value) && over90Qty.equals(other.over90Qty) && over90Value.equals(other.over90Value) && totalQty.equals(other.totalQty) && totalValue.equals(other.totalValue);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.itemId, this.itemName, this.warehouseId, this.d0To30Qty, this.d0To30Value, this.d31To60Qty, this.d31To60Value, this.d61To90Qty, this.d61To90Value, this.over90Qty, this.over90Value, this.totalQty, this.totalValue);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ItemIdStage builder() {
    return new Builder();
  }

  public interface ItemIdStage {
    ItemNameStage itemId(@NotNull String itemId);

    Builder from(PostV1ReportsStockAgingResponseRowsItem other);
  }

  public interface ItemNameStage {
    WarehouseIdStage itemName(@NotNull String itemName);
  }

  public interface WarehouseIdStage {
    D0To30QtyStage warehouseId(@NotNull String warehouseId);
  }

  public interface D0To30QtyStage {
    D0To30ValueStage d0To30Qty(@NotNull String d0To30Qty);
  }

  public interface D0To30ValueStage {
    D31To60QtyStage d0To30Value(@NotNull String d0To30Value);
  }

  public interface D31To60QtyStage {
    D31To60ValueStage d31To60Qty(@NotNull String d31To60Qty);
  }

  public interface D31To60ValueStage {
    D61To90QtyStage d31To60Value(@NotNull String d31To60Value);
  }

  public interface D61To90QtyStage {
    D61To90ValueStage d61To90Qty(@NotNull String d61To90Qty);
  }

  public interface D61To90ValueStage {
    Over90QtyStage d61To90Value(@NotNull String d61To90Value);
  }

  public interface Over90QtyStage {
    Over90ValueStage over90Qty(@NotNull String over90Qty);
  }

  public interface Over90ValueStage {
    TotalQtyStage over90Value(@NotNull String over90Value);
  }

  public interface TotalQtyStage {
    TotalValueStage totalQty(@NotNull String totalQty);
  }

  public interface TotalValueStage {
    _FinalStage totalValue(@NotNull String totalValue);
  }

  public interface _FinalStage {
    PostV1ReportsStockAgingResponseRowsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ItemIdStage, ItemNameStage, WarehouseIdStage, D0To30QtyStage, D0To30ValueStage, D31To60QtyStage, D31To60ValueStage, D61To90QtyStage, D61To90ValueStage, Over90QtyStage, Over90ValueStage, TotalQtyStage, TotalValueStage, _FinalStage {
    private String itemId;

    private String itemName;

    private String warehouseId;

    private String d0To30Qty;

    private String d0To30Value;

    private String d31To60Qty;

    private String d31To60Value;

    private String d61To90Qty;

    private String d61To90Value;

    private String over90Qty;

    private String over90Value;

    private String totalQty;

    private String totalValue;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1ReportsStockAgingResponseRowsItem other) {
      itemId(other.getItemId());
      itemName(other.getItemName());
      warehouseId(other.getWarehouseId());
      d0To30Qty(other.getD0To30Qty());
      d0To30Value(other.getD0To30Value());
      d31To60Qty(other.getD31To60Qty());
      d31To60Value(other.getD31To60Value());
      d61To90Qty(other.getD61To90Qty());
      d61To90Value(other.getD61To90Value());
      over90Qty(other.getOver90Qty());
      over90Value(other.getOver90Value());
      totalQty(other.getTotalQty());
      totalValue(other.getTotalValue());
      return this;
    }

    @java.lang.Override
    @JsonSetter("itemId")
    public ItemNameStage itemId(@NotNull String itemId) {
      this.itemId = Objects.requireNonNull(itemId, "itemId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("itemName")
    public WarehouseIdStage itemName(@NotNull String itemName) {
      this.itemName = Objects.requireNonNull(itemName, "itemName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("warehouseId")
    public D0To30QtyStage warehouseId(@NotNull String warehouseId) {
      this.warehouseId = Objects.requireNonNull(warehouseId, "warehouseId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d0to30Qty")
    public D0To30ValueStage d0To30Qty(@NotNull String d0To30Qty) {
      this.d0To30Qty = Objects.requireNonNull(d0To30Qty, "d0To30Qty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d0to30Value")
    public D31To60QtyStage d0To30Value(@NotNull String d0To30Value) {
      this.d0To30Value = Objects.requireNonNull(d0To30Value, "d0To30Value must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d31to60Qty")
    public D31To60ValueStage d31To60Qty(@NotNull String d31To60Qty) {
      this.d31To60Qty = Objects.requireNonNull(d31To60Qty, "d31To60Qty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d31to60Value")
    public D61To90QtyStage d31To60Value(@NotNull String d31To60Value) {
      this.d31To60Value = Objects.requireNonNull(d31To60Value, "d31To60Value must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d61to90Qty")
    public D61To90ValueStage d61To90Qty(@NotNull String d61To90Qty) {
      this.d61To90Qty = Objects.requireNonNull(d61To90Qty, "d61To90Qty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("d61to90Value")
    public Over90QtyStage d61To90Value(@NotNull String d61To90Value) {
      this.d61To90Value = Objects.requireNonNull(d61To90Value, "d61To90Value must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("over90Qty")
    public Over90ValueStage over90Qty(@NotNull String over90Qty) {
      this.over90Qty = Objects.requireNonNull(over90Qty, "over90Qty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("over90Value")
    public TotalQtyStage over90Value(@NotNull String over90Value) {
      this.over90Value = Objects.requireNonNull(over90Value, "over90Value must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalQty")
    public TotalValueStage totalQty(@NotNull String totalQty) {
      this.totalQty = Objects.requireNonNull(totalQty, "totalQty must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalValue")
    public _FinalStage totalValue(@NotNull String totalValue) {
      this.totalValue = Objects.requireNonNull(totalValue, "totalValue must not be null");
      return this;
    }

    @java.lang.Override
    public PostV1ReportsStockAgingResponseRowsItem build() {
      return new PostV1ReportsStockAgingResponseRowsItem(itemId, itemName, warehouseId, d0To30Qty, d0To30Value, d31To60Qty, d31To60Value, d61To90Qty, d61To90Value, over90Qty, over90Value, totalQty, totalValue, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
