/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.capture.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1CaptureDocumentsExtractResponseStatus {
  public static final PostV1CaptureDocumentsExtractResponseStatus LINKED = new PostV1CaptureDocumentsExtractResponseStatus(Value.LINKED, "linked");

  public static final PostV1CaptureDocumentsExtractResponseStatus FAILED = new PostV1CaptureDocumentsExtractResponseStatus(Value.FAILED, "failed");

  public static final PostV1CaptureDocumentsExtractResponseStatus EXTRACTED = new PostV1CaptureDocumentsExtractResponseStatus(Value.EXTRACTED, "extracted");

  public static final PostV1CaptureDocumentsExtractResponseStatus PENDING = new PostV1CaptureDocumentsExtractResponseStatus(Value.PENDING, "pending");

  private final Value value;

  private final String string;

  PostV1CaptureDocumentsExtractResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1CaptureDocumentsExtractResponseStatus && this.string.equals(((PostV1CaptureDocumentsExtractResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LINKED:
        return visitor.visitLinked();
      case FAILED:
        return visitor.visitFailed();
      case EXTRACTED:
        return visitor.visitExtracted();
      case PENDING:
        return visitor.visitPending();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1CaptureDocumentsExtractResponseStatus valueOf(String value) {
    switch (value) {
      case "linked":
        return LINKED;
      case "failed":
        return FAILED;
      case "extracted":
        return EXTRACTED;
      case "pending":
        return PENDING;
      default:
        return new PostV1CaptureDocumentsExtractResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PENDING,

    EXTRACTED,

    FAILED,

    LINKED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPending();

    T visitExtracted();

    T visitFailed();

    T visitLinked();

    T visitUnknown(String unknownType);
  }
}
