/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.consolidation.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType {
  public static final IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType CREDIT_NOTE = new IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType(Value.CREDIT_NOTE, "credit_note");

  public static final IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType INVOICE = new IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType(Value.INVOICE, "invoice");

  private final Value value;

  private final String string;

  IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType(Value value,
      String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType && this.string.equals(((IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CREDIT_NOTE:
        return visitor.visitCreditNote();
      case INVOICE:
        return visitor.visitInvoice();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType valueOf(
      String value) {
    switch (value) {
      case "credit_note":
        return CREDIT_NOTE;
      case "invoice":
        return INVOICE;
      default:
        return new IntercompanyReportConsolidationResponseDirectionsItemDocumentsItemType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INVOICE,

    CREDIT_NOTE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInvoice();

    T visitCreditNote();

    T visitUnknown(String unknownType);
  }
}
