/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.reference.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1ReferenceVatResolveResponseScheme {
  public static final PostV1ReferenceVatResolveResponseScheme REVERSE_CHARGE = new PostV1ReferenceVatResolveResponseScheme(Value.REVERSE_CHARGE, "reverse_charge");

  public static final PostV1ReferenceVatResolveResponseScheme INTRA_EU_B2B = new PostV1ReferenceVatResolveResponseScheme(Value.INTRA_EU_B2B, "intra_eu_b2b");

  public static final PostV1ReferenceVatResolveResponseScheme IOSS = new PostV1ReferenceVatResolveResponseScheme(Value.IOSS, "ioss");

  public static final PostV1ReferenceVatResolveResponseScheme OSS_UNION = new PostV1ReferenceVatResolveResponseScheme(Value.OSS_UNION, "oss_union");

  public static final PostV1ReferenceVatResolveResponseScheme OUT_OF_SCOPE = new PostV1ReferenceVatResolveResponseScheme(Value.OUT_OF_SCOPE, "out_of_scope");

  public static final PostV1ReferenceVatResolveResponseScheme EXPORT = new PostV1ReferenceVatResolveResponseScheme(Value.EXPORT, "export");

  public static final PostV1ReferenceVatResolveResponseScheme MARKETPLACE_DEEMED = new PostV1ReferenceVatResolveResponseScheme(Value.MARKETPLACE_DEEMED, "marketplace_deemed");

  public static final PostV1ReferenceVatResolveResponseScheme DOMESTIC = new PostV1ReferenceVatResolveResponseScheme(Value.DOMESTIC, "domestic");

  private final Value value;

  private final String string;

  PostV1ReferenceVatResolveResponseScheme(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1ReferenceVatResolveResponseScheme && this.string.equals(((PostV1ReferenceVatResolveResponseScheme) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case REVERSE_CHARGE:
        return visitor.visitReverseCharge();
      case INTRA_EU_B2B:
        return visitor.visitIntraEuB2B();
      case IOSS:
        return visitor.visitIoss();
      case OSS_UNION:
        return visitor.visitOssUnion();
      case OUT_OF_SCOPE:
        return visitor.visitOutOfScope();
      case EXPORT:
        return visitor.visitExport();
      case MARKETPLACE_DEEMED:
        return visitor.visitMarketplaceDeemed();
      case DOMESTIC:
        return visitor.visitDomestic();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1ReferenceVatResolveResponseScheme valueOf(String value) {
    switch (value) {
      case "reverse_charge":
        return REVERSE_CHARGE;
      case "intra_eu_b2b":
        return INTRA_EU_B2B;
      case "ioss":
        return IOSS;
      case "oss_union":
        return OSS_UNION;
      case "out_of_scope":
        return OUT_OF_SCOPE;
      case "export":
        return EXPORT;
      case "marketplace_deemed":
        return MARKETPLACE_DEEMED;
      case "domestic":
        return DOMESTIC;
      default:
        return new PostV1ReferenceVatResolveResponseScheme(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DOMESTIC,

    INTRA_EU_B2B,

    REVERSE_CHARGE,

    OSS_UNION,

    IOSS,

    MARKETPLACE_DEEMED,

    EXPORT,

    OUT_OF_SCOPE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDomestic();

    T visitIntraEuB2B();

    T visitReverseCharge();

    T visitOssUnion();

    T visitIoss();

    T visitMarketplaceDeemed();

    T visitExport();

    T visitOutOfScope();

    T visitUnknown(String unknownType);
  }
}
