/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.reference.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem.Builder.class
)
public final class PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem {
  private final PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory category;

  private final String ratePercent;

  private final Map<String, Object> additionalProperties;

  private PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem(
      PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory category, String ratePercent,
      Map<String, Object> additionalProperties) {
    this.category = category;
    this.ratePercent = ratePercent;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("category")
  public PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory getCategory() {
    return category;
  }

  @JsonProperty("ratePercent")
  public String getRatePercent() {
    return ratePercent;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem && equalTo((PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem other) {
    return category.equals(other.category) && ratePercent.equals(other.ratePercent);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.category, this.ratePercent);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CategoryStage builder() {
    return new Builder();
  }

  public interface CategoryStage {
    RatePercentStage category(
        @NotNull PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory category);

    Builder from(PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem other);
  }

  public interface RatePercentStage {
    _FinalStage ratePercent(@NotNull String ratePercent);
  }

  public interface _FinalStage {
    PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CategoryStage, RatePercentStage, _FinalStage {
    private PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory category;

    private String ratePercent;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem other) {
      category(other.getCategory());
      ratePercent(other.getRatePercent());
      return this;
    }

    @java.lang.Override
    @JsonSetter("category")
    public RatePercentStage category(
        @NotNull PostV1ReferenceEuVatRatesSetOverridesRequestRatesItemCategory category) {
      this.category = Objects.requireNonNull(category, "category must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("ratePercent")
    public _FinalStage ratePercent(@NotNull String ratePercent) {
      this.ratePercent = Objects.requireNonNull(ratePercent, "ratePercent must not be null");
      return this;
    }

    @java.lang.Override
    public PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem build() {
      return new PostV1ReferenceEuVatRatesSetOverridesRequestRatesItem(category, ratePercent, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
