/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.reference.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class UnitsListReferenceRequestSortItemDir {
  public static final UnitsListReferenceRequestSortItemDir ASC = new UnitsListReferenceRequestSortItemDir(Value.ASC, "asc");

  public static final UnitsListReferenceRequestSortItemDir DESC = new UnitsListReferenceRequestSortItemDir(Value.DESC, "desc");

  private final Value value;

  private final String string;

  UnitsListReferenceRequestSortItemDir(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof UnitsListReferenceRequestSortItemDir && this.string.equals(((UnitsListReferenceRequestSortItemDir) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ASC:
        return visitor.visitAsc();
      case DESC:
        return visitor.visitDesc();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static UnitsListReferenceRequestSortItemDir valueOf(String value) {
    switch (value) {
      case "asc":
        return ASC;
      case "desc":
        return DESC;
      default:
        return new UnitsListReferenceRequestSortItemDir(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ASC,

    DESC,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAsc();

    T visitDesc();

    T visitUnknown(String unknownType);
  }
}
