/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class EuSmeThresholdGetDeclarationsResponseIntraEuStatus {
  public static final EuSmeThresholdGetDeclarationsResponseIntraEuStatus EXCEEDED = new EuSmeThresholdGetDeclarationsResponseIntraEuStatus(Value.EXCEEDED, "exceeded");

  public static final EuSmeThresholdGetDeclarationsResponseIntraEuStatus BELOW = new EuSmeThresholdGetDeclarationsResponseIntraEuStatus(Value.BELOW, "below");

  public static final EuSmeThresholdGetDeclarationsResponseIntraEuStatus APPROACHING = new EuSmeThresholdGetDeclarationsResponseIntraEuStatus(Value.APPROACHING, "approaching");

  private final Value value;

  private final String string;

  EuSmeThresholdGetDeclarationsResponseIntraEuStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof EuSmeThresholdGetDeclarationsResponseIntraEuStatus && this.string.equals(((EuSmeThresholdGetDeclarationsResponseIntraEuStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case EXCEEDED:
        return visitor.visitExceeded();
      case BELOW:
        return visitor.visitBelow();
      case APPROACHING:
        return visitor.visitApproaching();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static EuSmeThresholdGetDeclarationsResponseIntraEuStatus valueOf(String value) {
    switch (value) {
      case "exceeded":
        return EXCEEDED;
      case "below":
        return BELOW;
      case "approaching":
        return APPROACHING;
      default:
        return new EuSmeThresholdGetDeclarationsResponseIntraEuStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    BELOW,

    APPROACHING,

    EXCEEDED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitBelow();

    T visitApproaching();

    T visitExceeded();

    T visitUnknown(String unknownType);
  }
}
