/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = EuVatReturnComputeDeclarationsResponse.Builder.class
)
public final class EuVatReturnComputeDeclarationsResponse {
  private final String countryCode;

  private final String formKey;

  private final String formName;

  private final EuVatReturnComputeDeclarationsResponseFrequency frequency;

  private final String periodStart;

  private final String periodEnd;

  private final List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes;

  private final List<String> warnings;

  private final List<String> notes;

  private final String source;

  private final Map<String, Object> additionalProperties;

  private EuVatReturnComputeDeclarationsResponse(String countryCode, String formKey,
      String formName, EuVatReturnComputeDeclarationsResponseFrequency frequency,
      String periodStart, String periodEnd,
      List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes, List<String> warnings,
      List<String> notes, String source, Map<String, Object> additionalProperties) {
    this.countryCode = countryCode;
    this.formKey = formKey;
    this.formName = formName;
    this.frequency = frequency;
    this.periodStart = periodStart;
    this.periodEnd = periodEnd;
    this.boxes = boxes;
    this.warnings = warnings;
    this.notes = notes;
    this.source = source;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("countryCode")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("formKey")
  public String getFormKey() {
    return formKey;
  }

  @JsonProperty("formName")
  public String getFormName() {
    return formName;
  }

  @JsonProperty("frequency")
  public EuVatReturnComputeDeclarationsResponseFrequency getFrequency() {
    return frequency;
  }

  @JsonProperty("periodStart")
  public String getPeriodStart() {
    return periodStart;
  }

  @JsonProperty("periodEnd")
  public String getPeriodEnd() {
    return periodEnd;
  }

  @JsonProperty("boxes")
  public List<EuVatReturnComputeDeclarationsResponseBoxesItem> getBoxes() {
    return boxes;
  }

  @JsonProperty("warnings")
  public List<String> getWarnings() {
    return warnings;
  }

  @JsonProperty("notes")
  public List<String> getNotes() {
    return notes;
  }

  @JsonProperty("source")
  public String getSource() {
    return source;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof EuVatReturnComputeDeclarationsResponse && equalTo((EuVatReturnComputeDeclarationsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(EuVatReturnComputeDeclarationsResponse other) {
    return countryCode.equals(other.countryCode) && formKey.equals(other.formKey) && formName.equals(other.formName) && frequency.equals(other.frequency) && periodStart.equals(other.periodStart) && periodEnd.equals(other.periodEnd) && boxes.equals(other.boxes) && warnings.equals(other.warnings) && notes.equals(other.notes) && source.equals(other.source);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.countryCode, this.formKey, this.formName, this.frequency, this.periodStart, this.periodEnd, this.boxes, this.warnings, this.notes, this.source);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CountryCodeStage builder() {
    return new Builder();
  }

  public interface CountryCodeStage {
    FormKeyStage countryCode(@NotNull String countryCode);

    Builder from(EuVatReturnComputeDeclarationsResponse other);
  }

  public interface FormKeyStage {
    FormNameStage formKey(@NotNull String formKey);
  }

  public interface FormNameStage {
    FrequencyStage formName(@NotNull String formName);
  }

  public interface FrequencyStage {
    PeriodStartStage frequency(@NotNull EuVatReturnComputeDeclarationsResponseFrequency frequency);
  }

  public interface PeriodStartStage {
    PeriodEndStage periodStart(@NotNull String periodStart);
  }

  public interface PeriodEndStage {
    SourceStage periodEnd(@NotNull String periodEnd);
  }

  public interface SourceStage {
    _FinalStage source(@NotNull String source);
  }

  public interface _FinalStage {
    EuVatReturnComputeDeclarationsResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage boxes(List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes);

    _FinalStage addBoxes(EuVatReturnComputeDeclarationsResponseBoxesItem boxes);

    _FinalStage addAllBoxes(List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes);

    _FinalStage warnings(List<String> warnings);

    _FinalStage addWarnings(String warnings);

    _FinalStage addAllWarnings(List<String> warnings);

    _FinalStage notes(List<String> notes);

    _FinalStage addNotes(String notes);

    _FinalStage addAllNotes(List<String> notes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CountryCodeStage, FormKeyStage, FormNameStage, FrequencyStage, PeriodStartStage, PeriodEndStage, SourceStage, _FinalStage {
    private String countryCode;

    private String formKey;

    private String formName;

    private EuVatReturnComputeDeclarationsResponseFrequency frequency;

    private String periodStart;

    private String periodEnd;

    private String source;

    private List<String> notes = new ArrayList<>();

    private List<String> warnings = new ArrayList<>();

    private List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(EuVatReturnComputeDeclarationsResponse other) {
      countryCode(other.getCountryCode());
      formKey(other.getFormKey());
      formName(other.getFormName());
      frequency(other.getFrequency());
      periodStart(other.getPeriodStart());
      periodEnd(other.getPeriodEnd());
      boxes(other.getBoxes());
      warnings(other.getWarnings());
      notes(other.getNotes());
      source(other.getSource());
      return this;
    }

    @java.lang.Override
    @JsonSetter("countryCode")
    public FormKeyStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("formKey")
    public FormNameStage formKey(@NotNull String formKey) {
      this.formKey = Objects.requireNonNull(formKey, "formKey must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("formName")
    public FrequencyStage formName(@NotNull String formName) {
      this.formName = Objects.requireNonNull(formName, "formName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("frequency")
    public PeriodStartStage frequency(
        @NotNull EuVatReturnComputeDeclarationsResponseFrequency frequency) {
      this.frequency = Objects.requireNonNull(frequency, "frequency must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("periodStart")
    public PeriodEndStage periodStart(@NotNull String periodStart) {
      this.periodStart = Objects.requireNonNull(periodStart, "periodStart must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("periodEnd")
    public SourceStage periodEnd(@NotNull String periodEnd) {
      this.periodEnd = Objects.requireNonNull(periodEnd, "periodEnd must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source")
    public _FinalStage source(@NotNull String source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllNotes(List<String> notes) {
      if (notes != null) {
        this.notes.addAll(notes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addNotes(String notes) {
      this.notes.add(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(List<String> notes) {
      this.notes.clear();
      if (notes != null) {
        this.notes.addAll(notes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllWarnings(List<String> warnings) {
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addWarnings(String warnings) {
      this.warnings.add(warnings);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warnings",
        nulls = Nulls.SKIP
    )
    public _FinalStage warnings(List<String> warnings) {
      this.warnings.clear();
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllBoxes(List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes) {
      if (boxes != null) {
        this.boxes.addAll(boxes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addBoxes(EuVatReturnComputeDeclarationsResponseBoxesItem boxes) {
      this.boxes.add(boxes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "boxes",
        nulls = Nulls.SKIP
    )
    public _FinalStage boxes(List<EuVatReturnComputeDeclarationsResponseBoxesItem> boxes) {
      this.boxes.clear();
      if (boxes != null) {
        this.boxes.addAll(boxes);
      }
      return this;
    }

    @java.lang.Override
    public EuVatReturnComputeDeclarationsResponse build() {
      return new EuVatReturnComputeDeclarationsResponse(countryCode, formKey, formName, frequency, periodStart, periodEnd, boxes, warnings, notes, source, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
