/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LtFr0564ComputeDeclarationsResponseCounts.Builder.class
)
public final class LtFr0564ComputeDeclarationsResponseCounts {
  private final long salesInvoices;

  private final Map<String, Object> additionalProperties;

  private LtFr0564ComputeDeclarationsResponseCounts(long salesInvoices,
      Map<String, Object> additionalProperties) {
    this.salesInvoices = salesInvoices;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("salesInvoices")
  public long getSalesInvoices() {
    return salesInvoices;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LtFr0564ComputeDeclarationsResponseCounts && equalTo((LtFr0564ComputeDeclarationsResponseCounts) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LtFr0564ComputeDeclarationsResponseCounts other) {
    return salesInvoices == other.salesInvoices;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.salesInvoices);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SalesInvoicesStage builder() {
    return new Builder();
  }

  public interface SalesInvoicesStage {
    _FinalStage salesInvoices(long salesInvoices);

    Builder from(LtFr0564ComputeDeclarationsResponseCounts other);
  }

  public interface _FinalStage {
    LtFr0564ComputeDeclarationsResponseCounts build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SalesInvoicesStage, _FinalStage {
    private long salesInvoices;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LtFr0564ComputeDeclarationsResponseCounts other) {
      salesInvoices(other.getSalesInvoices());
      return this;
    }

    @java.lang.Override
    @JsonSetter("salesInvoices")
    public _FinalStage salesInvoices(long salesInvoices) {
      this.salesInvoices = salesInvoices;
      return this;
    }

    @java.lang.Override
    public LtFr0564ComputeDeclarationsResponseCounts build() {
      return new LtFr0564ComputeDeclarationsResponseCounts(salesInvoices, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
