/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class LtGpm312ComputeDeclarationsResponsePayoutTiming {
  public static final LtGpm312ComputeDeclarationsResponsePayoutTiming SAME_MONTH = new LtGpm312ComputeDeclarationsResponsePayoutTiming(Value.SAME_MONTH, "same-month");

  public static final LtGpm312ComputeDeclarationsResponsePayoutTiming NEXT_MONTH = new LtGpm312ComputeDeclarationsResponsePayoutTiming(Value.NEXT_MONTH, "next-month");

  private final Value value;

  private final String string;

  LtGpm312ComputeDeclarationsResponsePayoutTiming(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof LtGpm312ComputeDeclarationsResponsePayoutTiming && this.string.equals(((LtGpm312ComputeDeclarationsResponsePayoutTiming) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SAME_MONTH:
        return visitor.visitSameMonth();
      case NEXT_MONTH:
        return visitor.visitNextMonth();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static LtGpm312ComputeDeclarationsResponsePayoutTiming valueOf(String value) {
    switch (value) {
      case "same-month":
        return SAME_MONTH;
      case "next-month":
        return NEXT_MONTH;
      default:
        return new LtGpm312ComputeDeclarationsResponsePayoutTiming(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    SAME_MONTH,

    NEXT_MONTH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitSameMonth();

    T visitNextMonth();

    T visitUnknown(String unknownType);
  }
}
