/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LtPln204ComputeDeclarationsResponse.Builder.class
)
public final class LtPln204ComputeDeclarationsResponse {
  private final long year;

  private final String periodStart;

  private final String periodEnd;

  private final LtPln204ComputeDeclarationsResponseVariant variant;

  private final String registrationNumber;

  private final String companyName;

  private final String ratePercent;

  private final String rateCode;

  private final boolean smallEntity;

  private final LtPln204ComputeDeclarationsResponseCriteria criteria;

  private final String totalIncome;

  private final Map<String, String> boxes;

  private final List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS;

  private final List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ;

  private final List<LtPln204ComputeDeclarationsResponseLinesItem> lines;

  private final List<String> warnings;

  private final List<String> notes;

  private final String source;

  private final Map<String, Object> additionalProperties;

  private LtPln204ComputeDeclarationsResponse(long year, String periodStart, String periodEnd,
      LtPln204ComputeDeclarationsResponseVariant variant, String registrationNumber,
      String companyName, String ratePercent, String rateCode, boolean smallEntity,
      LtPln204ComputeDeclarationsResponseCriteria criteria, String totalIncome,
      Map<String, String> boxes, List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS,
      List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ,
      List<LtPln204ComputeDeclarationsResponseLinesItem> lines, List<String> warnings,
      List<String> notes, String source, Map<String, Object> additionalProperties) {
    this.year = year;
    this.periodStart = periodStart;
    this.periodEnd = periodEnd;
    this.variant = variant;
    this.registrationNumber = registrationNumber;
    this.companyName = companyName;
    this.ratePercent = ratePercent;
    this.rateCode = rateCode;
    this.smallEntity = smallEntity;
    this.criteria = criteria;
    this.totalIncome = totalIncome;
    this.boxes = boxes;
    this.annexS = annexS;
    this.annexZ = annexZ;
    this.lines = lines;
    this.warnings = warnings;
    this.notes = notes;
    this.source = source;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("year")
  public long getYear() {
    return year;
  }

  @JsonProperty("periodStart")
  public String getPeriodStart() {
    return periodStart;
  }

  @JsonProperty("periodEnd")
  public String getPeriodEnd() {
    return periodEnd;
  }

  @JsonProperty("variant")
  public LtPln204ComputeDeclarationsResponseVariant getVariant() {
    return variant;
  }

  @JsonProperty("registrationNumber")
  public String getRegistrationNumber() {
    return registrationNumber;
  }

  @JsonProperty("companyName")
  public String getCompanyName() {
    return companyName;
  }

  @JsonProperty("ratePercent")
  public String getRatePercent() {
    return ratePercent;
  }

  @JsonProperty("rateCode")
  public String getRateCode() {
    return rateCode;
  }

  @JsonProperty("smallEntity")
  public boolean getSmallEntity() {
    return smallEntity;
  }

  @JsonProperty("criteria")
  public LtPln204ComputeDeclarationsResponseCriteria getCriteria() {
    return criteria;
  }

  @JsonProperty("totalIncome")
  public String getTotalIncome() {
    return totalIncome;
  }

  @JsonProperty("boxes")
  public Map<String, String> getBoxes() {
    return boxes;
  }

  @JsonProperty("annexS")
  public List<LtPln204ComputeDeclarationsResponseAnnexSItem> getAnnexS() {
    return annexS;
  }

  @JsonProperty("annexZ")
  public List<LtPln204ComputeDeclarationsResponseAnnexZItem> getAnnexZ() {
    return annexZ;
  }

  @JsonProperty("lines")
  public List<LtPln204ComputeDeclarationsResponseLinesItem> getLines() {
    return lines;
  }

  @JsonProperty("warnings")
  public List<String> getWarnings() {
    return warnings;
  }

  @JsonProperty("notes")
  public List<String> getNotes() {
    return notes;
  }

  @JsonProperty("source")
  public String getSource() {
    return source;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LtPln204ComputeDeclarationsResponse && equalTo((LtPln204ComputeDeclarationsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LtPln204ComputeDeclarationsResponse other) {
    return year == other.year && periodStart.equals(other.periodStart) && periodEnd.equals(other.periodEnd) && variant.equals(other.variant) && registrationNumber.equals(other.registrationNumber) && companyName.equals(other.companyName) && ratePercent.equals(other.ratePercent) && rateCode.equals(other.rateCode) && smallEntity == other.smallEntity && criteria.equals(other.criteria) && totalIncome.equals(other.totalIncome) && boxes.equals(other.boxes) && annexS.equals(other.annexS) && annexZ.equals(other.annexZ) && lines.equals(other.lines) && warnings.equals(other.warnings) && notes.equals(other.notes) && source.equals(other.source);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.year, this.periodStart, this.periodEnd, this.variant, this.registrationNumber, this.companyName, this.ratePercent, this.rateCode, this.smallEntity, this.criteria, this.totalIncome, this.boxes, this.annexS, this.annexZ, this.lines, this.warnings, this.notes, this.source);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static YearStage builder() {
    return new Builder();
  }

  public interface YearStage {
    PeriodStartStage year(long year);

    Builder from(LtPln204ComputeDeclarationsResponse other);
  }

  public interface PeriodStartStage {
    PeriodEndStage periodStart(@NotNull String periodStart);
  }

  public interface PeriodEndStage {
    VariantStage periodEnd(@NotNull String periodEnd);
  }

  public interface VariantStage {
    RegistrationNumberStage variant(@NotNull LtPln204ComputeDeclarationsResponseVariant variant);
  }

  public interface RegistrationNumberStage {
    CompanyNameStage registrationNumber(@NotNull String registrationNumber);
  }

  public interface CompanyNameStage {
    RatePercentStage companyName(@NotNull String companyName);
  }

  public interface RatePercentStage {
    RateCodeStage ratePercent(@NotNull String ratePercent);
  }

  public interface RateCodeStage {
    SmallEntityStage rateCode(@NotNull String rateCode);
  }

  public interface SmallEntityStage {
    CriteriaStage smallEntity(boolean smallEntity);
  }

  public interface CriteriaStage {
    TotalIncomeStage criteria(@NotNull LtPln204ComputeDeclarationsResponseCriteria criteria);
  }

  public interface TotalIncomeStage {
    SourceStage totalIncome(@NotNull String totalIncome);
  }

  public interface SourceStage {
    _FinalStage source(@NotNull String source);
  }

  public interface _FinalStage {
    LtPln204ComputeDeclarationsResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage boxes(Map<String, String> boxes);

    _FinalStage putAllBoxes(Map<String, String> boxes);

    _FinalStage boxes(String key, String value);

    _FinalStage annexS(List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS);

    _FinalStage addAnnexS(LtPln204ComputeDeclarationsResponseAnnexSItem annexS);

    _FinalStage addAllAnnexS(List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS);

    _FinalStage annexZ(List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ);

    _FinalStage addAnnexZ(LtPln204ComputeDeclarationsResponseAnnexZItem annexZ);

    _FinalStage addAllAnnexZ(List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ);

    _FinalStage lines(List<LtPln204ComputeDeclarationsResponseLinesItem> lines);

    _FinalStage addLines(LtPln204ComputeDeclarationsResponseLinesItem lines);

    _FinalStage addAllLines(List<LtPln204ComputeDeclarationsResponseLinesItem> lines);

    _FinalStage warnings(List<String> warnings);

    _FinalStage addWarnings(String warnings);

    _FinalStage addAllWarnings(List<String> warnings);

    _FinalStage notes(List<String> notes);

    _FinalStage addNotes(String notes);

    _FinalStage addAllNotes(List<String> notes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements YearStage, PeriodStartStage, PeriodEndStage, VariantStage, RegistrationNumberStage, CompanyNameStage, RatePercentStage, RateCodeStage, SmallEntityStage, CriteriaStage, TotalIncomeStage, SourceStage, _FinalStage {
    private long year;

    private String periodStart;

    private String periodEnd;

    private LtPln204ComputeDeclarationsResponseVariant variant;

    private String registrationNumber;

    private String companyName;

    private String ratePercent;

    private String rateCode;

    private boolean smallEntity;

    private LtPln204ComputeDeclarationsResponseCriteria criteria;

    private String totalIncome;

    private String source;

    private List<String> notes = new ArrayList<>();

    private List<String> warnings = new ArrayList<>();

    private List<LtPln204ComputeDeclarationsResponseLinesItem> lines = new ArrayList<>();

    private List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ = new ArrayList<>();

    private List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS = new ArrayList<>();

    private Map<String, String> boxes = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LtPln204ComputeDeclarationsResponse other) {
      year(other.getYear());
      periodStart(other.getPeriodStart());
      periodEnd(other.getPeriodEnd());
      variant(other.getVariant());
      registrationNumber(other.getRegistrationNumber());
      companyName(other.getCompanyName());
      ratePercent(other.getRatePercent());
      rateCode(other.getRateCode());
      smallEntity(other.getSmallEntity());
      criteria(other.getCriteria());
      totalIncome(other.getTotalIncome());
      boxes(other.getBoxes());
      annexS(other.getAnnexS());
      annexZ(other.getAnnexZ());
      lines(other.getLines());
      warnings(other.getWarnings());
      notes(other.getNotes());
      source(other.getSource());
      return this;
    }

    @java.lang.Override
    @JsonSetter("year")
    public PeriodStartStage year(long year) {
      this.year = year;
      return this;
    }

    @java.lang.Override
    @JsonSetter("periodStart")
    public PeriodEndStage periodStart(@NotNull String periodStart) {
      this.periodStart = Objects.requireNonNull(periodStart, "periodStart must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("periodEnd")
    public VariantStage periodEnd(@NotNull String periodEnd) {
      this.periodEnd = Objects.requireNonNull(periodEnd, "periodEnd must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("variant")
    public RegistrationNumberStage variant(
        @NotNull LtPln204ComputeDeclarationsResponseVariant variant) {
      this.variant = Objects.requireNonNull(variant, "variant must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("registrationNumber")
    public CompanyNameStage registrationNumber(@NotNull String registrationNumber) {
      this.registrationNumber = Objects.requireNonNull(registrationNumber, "registrationNumber must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("companyName")
    public RatePercentStage companyName(@NotNull String companyName) {
      this.companyName = Objects.requireNonNull(companyName, "companyName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("ratePercent")
    public RateCodeStage ratePercent(@NotNull String ratePercent) {
      this.ratePercent = Objects.requireNonNull(ratePercent, "ratePercent must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("rateCode")
    public SmallEntityStage rateCode(@NotNull String rateCode) {
      this.rateCode = Objects.requireNonNull(rateCode, "rateCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("smallEntity")
    public CriteriaStage smallEntity(boolean smallEntity) {
      this.smallEntity = smallEntity;
      return this;
    }

    @java.lang.Override
    @JsonSetter("criteria")
    public TotalIncomeStage criteria(
        @NotNull LtPln204ComputeDeclarationsResponseCriteria criteria) {
      this.criteria = Objects.requireNonNull(criteria, "criteria must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalIncome")
    public SourceStage totalIncome(@NotNull String totalIncome) {
      this.totalIncome = Objects.requireNonNull(totalIncome, "totalIncome must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source")
    public _FinalStage source(@NotNull String source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllNotes(List<String> notes) {
      if (notes != null) {
        this.notes.addAll(notes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addNotes(String notes) {
      this.notes.add(notes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "notes",
        nulls = Nulls.SKIP
    )
    public _FinalStage notes(List<String> notes) {
      this.notes.clear();
      if (notes != null) {
        this.notes.addAll(notes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllWarnings(List<String> warnings) {
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addWarnings(String warnings) {
      this.warnings.add(warnings);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warnings",
        nulls = Nulls.SKIP
    )
    public _FinalStage warnings(List<String> warnings) {
      this.warnings.clear();
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLines(List<LtPln204ComputeDeclarationsResponseLinesItem> lines) {
      if (lines != null) {
        this.lines.addAll(lines);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addLines(LtPln204ComputeDeclarationsResponseLinesItem lines) {
      this.lines.add(lines);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lines",
        nulls = Nulls.SKIP
    )
    public _FinalStage lines(List<LtPln204ComputeDeclarationsResponseLinesItem> lines) {
      this.lines.clear();
      if (lines != null) {
        this.lines.addAll(lines);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllAnnexZ(List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ) {
      if (annexZ != null) {
        this.annexZ.addAll(annexZ);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAnnexZ(LtPln204ComputeDeclarationsResponseAnnexZItem annexZ) {
      this.annexZ.add(annexZ);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "annexZ",
        nulls = Nulls.SKIP
    )
    public _FinalStage annexZ(List<LtPln204ComputeDeclarationsResponseAnnexZItem> annexZ) {
      this.annexZ.clear();
      if (annexZ != null) {
        this.annexZ.addAll(annexZ);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllAnnexS(List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS) {
      if (annexS != null) {
        this.annexS.addAll(annexS);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAnnexS(LtPln204ComputeDeclarationsResponseAnnexSItem annexS) {
      this.annexS.add(annexS);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "annexS",
        nulls = Nulls.SKIP
    )
    public _FinalStage annexS(List<LtPln204ComputeDeclarationsResponseAnnexSItem> annexS) {
      this.annexS.clear();
      if (annexS != null) {
        this.annexS.addAll(annexS);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage boxes(String key, String value) {
      this.boxes.put(key, value);
      return this;
    }

    @java.lang.Override
    public _FinalStage putAllBoxes(Map<String, String> boxes) {
      if (boxes != null) {
        this.boxes.putAll(boxes);
      }
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "boxes",
        nulls = Nulls.SKIP
    )
    public _FinalStage boxes(Map<String, String> boxes) {
      this.boxes.clear();
      if (boxes != null) {
        this.boxes.putAll(boxes);
      }
      return this;
    }

    @java.lang.Override
    public LtPln204ComputeDeclarationsResponse build() {
      return new LtPln204ComputeDeclarationsResponse(year, periodStart, periodEnd, variant, registrationNumber, companyName, ratePercent, rateCode, smallEntity, criteria, totalIncome, boxes, annexS, annexZ, lines, warnings, notes, source, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
