/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1DeclarationsEuOssComputeResponseRowsItem.Builder.class
)
public final class PostV1DeclarationsEuOssComputeResponseRowsItem {
  private final String countryCode;

  private final PostV1DeclarationsEuOssComputeResponseRowsItemRateType rateType;

  private final String vatRatePercent;

  private final String taxableAmount;

  private final String vatAmount;

  private final long documents;

  private final Map<String, Object> additionalProperties;

  private PostV1DeclarationsEuOssComputeResponseRowsItem(String countryCode,
      PostV1DeclarationsEuOssComputeResponseRowsItemRateType rateType, String vatRatePercent,
      String taxableAmount, String vatAmount, long documents,
      Map<String, Object> additionalProperties) {
    this.countryCode = countryCode;
    this.rateType = rateType;
    this.vatRatePercent = vatRatePercent;
    this.taxableAmount = taxableAmount;
    this.vatAmount = vatAmount;
    this.documents = documents;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("countryCode")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("rateType")
  public PostV1DeclarationsEuOssComputeResponseRowsItemRateType getRateType() {
    return rateType;
  }

  @JsonProperty("vatRatePercent")
  public String getVatRatePercent() {
    return vatRatePercent;
  }

  @JsonProperty("taxableAmount")
  public String getTaxableAmount() {
    return taxableAmount;
  }

  @JsonProperty("vatAmount")
  public String getVatAmount() {
    return vatAmount;
  }

  @JsonProperty("documents")
  public long getDocuments() {
    return documents;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1DeclarationsEuOssComputeResponseRowsItem && equalTo((PostV1DeclarationsEuOssComputeResponseRowsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1DeclarationsEuOssComputeResponseRowsItem other) {
    return countryCode.equals(other.countryCode) && rateType.equals(other.rateType) && vatRatePercent.equals(other.vatRatePercent) && taxableAmount.equals(other.taxableAmount) && vatAmount.equals(other.vatAmount) && documents == other.documents;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.countryCode, this.rateType, this.vatRatePercent, this.taxableAmount, this.vatAmount, this.documents);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CountryCodeStage builder() {
    return new Builder();
  }

  public interface CountryCodeStage {
    RateTypeStage countryCode(@NotNull String countryCode);

    Builder from(PostV1DeclarationsEuOssComputeResponseRowsItem other);
  }

  public interface RateTypeStage {
    VatRatePercentStage rateType(
        @NotNull PostV1DeclarationsEuOssComputeResponseRowsItemRateType rateType);
  }

  public interface VatRatePercentStage {
    TaxableAmountStage vatRatePercent(@NotNull String vatRatePercent);
  }

  public interface TaxableAmountStage {
    VatAmountStage taxableAmount(@NotNull String taxableAmount);
  }

  public interface VatAmountStage {
    DocumentsStage vatAmount(@NotNull String vatAmount);
  }

  public interface DocumentsStage {
    _FinalStage documents(long documents);
  }

  public interface _FinalStage {
    PostV1DeclarationsEuOssComputeResponseRowsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CountryCodeStage, RateTypeStage, VatRatePercentStage, TaxableAmountStage, VatAmountStage, DocumentsStage, _FinalStage {
    private String countryCode;

    private PostV1DeclarationsEuOssComputeResponseRowsItemRateType rateType;

    private String vatRatePercent;

    private String taxableAmount;

    private String vatAmount;

    private long documents;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1DeclarationsEuOssComputeResponseRowsItem other) {
      countryCode(other.getCountryCode());
      rateType(other.getRateType());
      vatRatePercent(other.getVatRatePercent());
      taxableAmount(other.getTaxableAmount());
      vatAmount(other.getVatAmount());
      documents(other.getDocuments());
      return this;
    }

    @java.lang.Override
    @JsonSetter("countryCode")
    public RateTypeStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("rateType")
    public VatRatePercentStage rateType(
        @NotNull PostV1DeclarationsEuOssComputeResponseRowsItemRateType rateType) {
      this.rateType = Objects.requireNonNull(rateType, "rateType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("vatRatePercent")
    public TaxableAmountStage vatRatePercent(@NotNull String vatRatePercent) {
      this.vatRatePercent = Objects.requireNonNull(vatRatePercent, "vatRatePercent must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("taxableAmount")
    public VatAmountStage taxableAmount(@NotNull String taxableAmount) {
      this.taxableAmount = Objects.requireNonNull(taxableAmount, "taxableAmount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("vatAmount")
    public DocumentsStage vatAmount(@NotNull String vatAmount) {
      this.vatAmount = Objects.requireNonNull(vatAmount, "vatAmount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("documents")
    public _FinalStage documents(long documents) {
      this.documents = documents;
      return this;
    }

    @java.lang.Override
    public PostV1DeclarationsEuOssComputeResponseRowsItem build() {
      return new PostV1DeclarationsEuOssComputeResponseRowsItem(countryCode, rateType, vatRatePercent, taxableAmount, vatAmount, documents, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
