/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1DeclarationsLtSdFfdataResponse.Builder.class
)
public final class PostV1DeclarationsLtSdFfdataResponse {
  private final PostV1DeclarationsLtSdFfdataResponseType type;

  private final String fileName;

  private final String xml;

  private final long rows;

  private final long pageCount;

  private final List<String> warnings;

  private final Map<String, Object> additionalProperties;

  private PostV1DeclarationsLtSdFfdataResponse(PostV1DeclarationsLtSdFfdataResponseType type,
      String fileName, String xml, long rows, long pageCount, List<String> warnings,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.fileName = fileName;
    this.xml = xml;
    this.rows = rows;
    this.pageCount = pageCount;
    this.warnings = warnings;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public PostV1DeclarationsLtSdFfdataResponseType getType() {
    return type;
  }

  @JsonProperty("fileName")
  public String getFileName() {
    return fileName;
  }

  @JsonProperty("xml")
  public String getXml() {
    return xml;
  }

  @JsonProperty("rows")
  public long getRows() {
    return rows;
  }

  @JsonProperty("pageCount")
  public long getPageCount() {
    return pageCount;
  }

  @JsonProperty("warnings")
  public List<String> getWarnings() {
    return warnings;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1DeclarationsLtSdFfdataResponse && equalTo((PostV1DeclarationsLtSdFfdataResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1DeclarationsLtSdFfdataResponse other) {
    return type.equals(other.type) && fileName.equals(other.fileName) && xml.equals(other.xml) && rows == other.rows && pageCount == other.pageCount && warnings.equals(other.warnings);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.fileName, this.xml, this.rows, this.pageCount, this.warnings);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    FileNameStage type(@NotNull PostV1DeclarationsLtSdFfdataResponseType type);

    Builder from(PostV1DeclarationsLtSdFfdataResponse other);
  }

  public interface FileNameStage {
    XmlStage fileName(@NotNull String fileName);
  }

  public interface XmlStage {
    RowsStage xml(@NotNull String xml);
  }

  public interface RowsStage {
    PageCountStage rows(long rows);
  }

  public interface PageCountStage {
    _FinalStage pageCount(long pageCount);
  }

  public interface _FinalStage {
    PostV1DeclarationsLtSdFfdataResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage warnings(List<String> warnings);

    _FinalStage addWarnings(String warnings);

    _FinalStage addAllWarnings(List<String> warnings);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, FileNameStage, XmlStage, RowsStage, PageCountStage, _FinalStage {
    private PostV1DeclarationsLtSdFfdataResponseType type;

    private String fileName;

    private String xml;

    private long rows;

    private long pageCount;

    private List<String> warnings = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1DeclarationsLtSdFfdataResponse other) {
      type(other.getType());
      fileName(other.getFileName());
      xml(other.getXml());
      rows(other.getRows());
      pageCount(other.getPageCount());
      warnings(other.getWarnings());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public FileNameStage type(@NotNull PostV1DeclarationsLtSdFfdataResponseType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("fileName")
    public XmlStage fileName(@NotNull String fileName) {
      this.fileName = Objects.requireNonNull(fileName, "fileName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("xml")
    public RowsStage xml(@NotNull String xml) {
      this.xml = Objects.requireNonNull(xml, "xml must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("rows")
    public PageCountStage rows(long rows) {
      this.rows = rows;
      return this;
    }

    @java.lang.Override
    @JsonSetter("pageCount")
    public _FinalStage pageCount(long pageCount) {
      this.pageCount = pageCount;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllWarnings(List<String> warnings) {
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addWarnings(String warnings) {
      this.warnings.add(warnings);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "warnings",
        nulls = Nulls.SKIP
    )
    public _FinalStage warnings(List<String> warnings) {
      this.warnings.clear();
      if (warnings != null) {
        this.warnings.addAll(warnings);
      }
      return this;
    }

    @java.lang.Override
    public PostV1DeclarationsLtSdFfdataResponse build() {
      return new PostV1DeclarationsLtSdFfdataResponse(type, fileName, xml, rows, pageCount, warnings, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
