/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.bank.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1BankSettlementsLinkRequest.Builder.class
)
public final class PostV1BankSettlementsLinkRequest {
  private final String id;

  private final String bankTransactionId;

  private final Map<String, Object> additionalProperties;

  private PostV1BankSettlementsLinkRequest(String id, String bankTransactionId,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.bankTransactionId = bankTransactionId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("bankTransactionId")
  public String getBankTransactionId() {
    return bankTransactionId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1BankSettlementsLinkRequest && equalTo((PostV1BankSettlementsLinkRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1BankSettlementsLinkRequest other) {
    return id.equals(other.id) && bankTransactionId.equals(other.bankTransactionId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.bankTransactionId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    BankTransactionIdStage id(@NotNull String id);

    Builder from(PostV1BankSettlementsLinkRequest other);
  }

  public interface BankTransactionIdStage {
    _FinalStage bankTransactionId(@NotNull String bankTransactionId);
  }

  public interface _FinalStage {
    PostV1BankSettlementsLinkRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, BankTransactionIdStage, _FinalStage {
    private String id;

    private String bankTransactionId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1BankSettlementsLinkRequest other) {
      id(other.getId());
      bankTransactionId(other.getBankTransactionId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public BankTransactionIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("bankTransactionId")
    public _FinalStage bankTransactionId(@NotNull String bankTransactionId) {
      this.bankTransactionId = Objects.requireNonNull(bankTransactionId, "bankTransactionId must not be null");
      return this;
    }

    @java.lang.Override
    public PostV1BankSettlementsLinkRequest build() {
      return new PostV1BankSettlementsLinkRequest(id, bankTransactionId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
