/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.billing.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1BillingAccountGetResponseStatus {
  public static final PostV1BillingAccountGetResponseStatus SUSPENDED = new PostV1BillingAccountGetResponseStatus(Value.SUSPENDED, "suspended");

  public static final PostV1BillingAccountGetResponseStatus TRIAL = new PostV1BillingAccountGetResponseStatus(Value.TRIAL, "trial");

  public static final PostV1BillingAccountGetResponseStatus ACTIVE = new PostV1BillingAccountGetResponseStatus(Value.ACTIVE, "active");

  private final Value value;

  private final String string;

  PostV1BillingAccountGetResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1BillingAccountGetResponseStatus && this.string.equals(((PostV1BillingAccountGetResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SUSPENDED:
        return visitor.visitSuspended();
      case TRIAL:
        return visitor.visitTrial();
      case ACTIVE:
        return visitor.visitActive();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1BillingAccountGetResponseStatus valueOf(String value) {
    switch (value) {
      case "suspended":
        return SUSPENDED;
      case "trial":
        return TRIAL;
      case "active":
        return ACTIVE;
      default:
        return new PostV1BillingAccountGetResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    TRIAL,

    ACTIVE,

    SUSPENDED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitTrial();

    T visitActive();

    T visitSuspended();

    T visitUnknown(String unknownType);
  }
}
