/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.ledger.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class StatementRowsListLedgerResponseAccountsItemSource {
  public static final StatementRowsListLedgerResponseAccountsItemSource MAPPING = new StatementRowsListLedgerResponseAccountsItemSource(Value.MAPPING, "mapping");

  public static final StatementRowsListLedgerResponseAccountsItemSource DEFAULT = new StatementRowsListLedgerResponseAccountsItemSource(Value.DEFAULT, "default");

  private final Value value;

  private final String string;

  StatementRowsListLedgerResponseAccountsItemSource(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof StatementRowsListLedgerResponseAccountsItemSource && this.string.equals(((StatementRowsListLedgerResponseAccountsItemSource) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MAPPING:
        return visitor.visitMapping();
      case DEFAULT:
        return visitor.visitDefault();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static StatementRowsListLedgerResponseAccountsItemSource valueOf(String value) {
    switch (value) {
      case "mapping":
        return MAPPING;
      case "default":
        return DEFAULT;
      default:
        return new StatementRowsListLedgerResponseAccountsItemSource(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MAPPING,

    DEFAULT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMapping();

    T visitDefault();

    T visitUnknown(String unknownType);
  }
}
