/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.catalog.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostV1CatalogItemsUpdateRequestTracking {
  public static final PostV1CatalogItemsUpdateRequestTracking LOT = new PostV1CatalogItemsUpdateRequestTracking(Value.LOT, "lot");

  public static final PostV1CatalogItemsUpdateRequestTracking SERIAL = new PostV1CatalogItemsUpdateRequestTracking(Value.SERIAL, "serial");

  public static final PostV1CatalogItemsUpdateRequestTracking NONE = new PostV1CatalogItemsUpdateRequestTracking(Value.NONE, "none");

  private final Value value;

  private final String string;

  PostV1CatalogItemsUpdateRequestTracking(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostV1CatalogItemsUpdateRequestTracking && this.string.equals(((PostV1CatalogItemsUpdateRequestTracking) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LOT:
        return visitor.visitLot();
      case SERIAL:
        return visitor.visitSerial();
      case NONE:
        return visitor.visitNone();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostV1CatalogItemsUpdateRequestTracking valueOf(String value) {
    switch (value) {
      case "lot":
        return LOT;
      case "serial":
        return SERIAL;
      case "none":
        return NONE;
      default:
        return new PostV1CatalogItemsUpdateRequestTracking(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NONE,

    LOT,

    SERIAL,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNone();

    T visitLot();

    T visitSerial();

    T visitUnknown(String unknownType);
  }
}
