/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.catalog.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.Nullable;
import com.nordlet.api.core.NullableNonemptyFilter;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1CatalogItemsGetResponse.Builder.class
)
public final class PostV1CatalogItemsGetResponse {
  private final String id;

  private final PostV1CatalogItemsGetResponseType type;

  private final String name;

  private final Optional<String> code;

  private final Optional<String> barcode;

  private final String unit;

  private final Optional<String> vatClassifierCode;

  private final Optional<String> vatRatePercent;

  private final Optional<String> salePriceExclVat;

  private final Optional<String> purchasePriceExclVat;

  private final Optional<String> cnCode;

  private final Optional<String> originCountry;

  private final Optional<String> netMassKg;

  private final Optional<String> supplementaryUnit;

  private final Optional<String> supplementaryQtyPerUnit;

  private final Optional<String> description;

  private final Optional<String> groupId;

  private final Optional<Map<String, Optional<String>>> attributes;

  private final Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations;

  private final List<PostV1CatalogItemsGetResponseComponentsItem> components;

  private final String createdAt;

  private final String updatedAt;

  private final Map<String, Object> additionalProperties;

  private PostV1CatalogItemsGetResponse(String id, PostV1CatalogItemsGetResponseType type,
      String name, Optional<String> code, Optional<String> barcode, String unit,
      Optional<String> vatClassifierCode, Optional<String> vatRatePercent,
      Optional<String> salePriceExclVat, Optional<String> purchasePriceExclVat,
      Optional<String> cnCode, Optional<String> originCountry, Optional<String> netMassKg,
      Optional<String> supplementaryUnit, Optional<String> supplementaryQtyPerUnit,
      Optional<String> description, Optional<String> groupId,
      Optional<Map<String, Optional<String>>> attributes,
      Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations,
      List<PostV1CatalogItemsGetResponseComponentsItem> components, String createdAt,
      String updatedAt, Map<String, Object> additionalProperties) {
    this.id = id;
    this.type = type;
    this.name = name;
    this.code = code;
    this.barcode = barcode;
    this.unit = unit;
    this.vatClassifierCode = vatClassifierCode;
    this.vatRatePercent = vatRatePercent;
    this.salePriceExclVat = salePriceExclVat;
    this.purchasePriceExclVat = purchasePriceExclVat;
    this.cnCode = cnCode;
    this.originCountry = originCountry;
    this.netMassKg = netMassKg;
    this.supplementaryUnit = supplementaryUnit;
    this.supplementaryQtyPerUnit = supplementaryQtyPerUnit;
    this.description = description;
    this.groupId = groupId;
    this.attributes = attributes;
    this.translations = translations;
    this.components = components;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("type")
  public PostV1CatalogItemsGetResponseType getType() {
    return type;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonIgnore
  public Optional<String> getCode() {
    if (code == null) {
      return Optional.empty();
    }
    return code;
  }

  @JsonIgnore
  public Optional<String> getBarcode() {
    if (barcode == null) {
      return Optional.empty();
    }
    return barcode;
  }

  @JsonProperty("unit")
  public String getUnit() {
    return unit;
  }

  @JsonIgnore
  public Optional<String> getVatClassifierCode() {
    if (vatClassifierCode == null) {
      return Optional.empty();
    }
    return vatClassifierCode;
  }

  @JsonIgnore
  public Optional<String> getVatRatePercent() {
    if (vatRatePercent == null) {
      return Optional.empty();
    }
    return vatRatePercent;
  }

  @JsonIgnore
  public Optional<String> getSalePriceExclVat() {
    if (salePriceExclVat == null) {
      return Optional.empty();
    }
    return salePriceExclVat;
  }

  @JsonIgnore
  public Optional<String> getPurchasePriceExclVat() {
    if (purchasePriceExclVat == null) {
      return Optional.empty();
    }
    return purchasePriceExclVat;
  }

  @JsonIgnore
  public Optional<String> getCnCode() {
    if (cnCode == null) {
      return Optional.empty();
    }
    return cnCode;
  }

  @JsonIgnore
  public Optional<String> getOriginCountry() {
    if (originCountry == null) {
      return Optional.empty();
    }
    return originCountry;
  }

  @JsonIgnore
  public Optional<String> getNetMassKg() {
    if (netMassKg == null) {
      return Optional.empty();
    }
    return netMassKg;
  }

  @JsonIgnore
  public Optional<String> getSupplementaryUnit() {
    if (supplementaryUnit == null) {
      return Optional.empty();
    }
    return supplementaryUnit;
  }

  @JsonIgnore
  public Optional<String> getSupplementaryQtyPerUnit() {
    if (supplementaryQtyPerUnit == null) {
      return Optional.empty();
    }
    return supplementaryQtyPerUnit;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<String> getGroupId() {
    if (groupId == null) {
      return Optional.empty();
    }
    return groupId;
  }

  @JsonIgnore
  public Optional<Map<String, Optional<String>>> getAttributes() {
    if (attributes == null) {
      return Optional.empty();
    }
    return attributes;
  }

  @JsonIgnore
  public Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> getTranslations(
      ) {
    if (translations == null) {
      return Optional.empty();
    }
    return translations;
  }

  @JsonProperty("components")
  public List<PostV1CatalogItemsGetResponseComponentsItem> getComponents() {
    return components;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updatedAt")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("code")
  private Optional<String> _getCode() {
    return code;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("barcode")
  private Optional<String> _getBarcode() {
    return barcode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("vatClassifierCode")
  private Optional<String> _getVatClassifierCode() {
    return vatClassifierCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("vatRatePercent")
  private Optional<String> _getVatRatePercent() {
    return vatRatePercent;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("salePriceExclVat")
  private Optional<String> _getSalePriceExclVat() {
    return salePriceExclVat;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("purchasePriceExclVat")
  private Optional<String> _getPurchasePriceExclVat() {
    return purchasePriceExclVat;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("cnCode")
  private Optional<String> _getCnCode() {
    return cnCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("originCountry")
  private Optional<String> _getOriginCountry() {
    return originCountry;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("netMassKg")
  private Optional<String> _getNetMassKg() {
    return netMassKg;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("supplementaryUnit")
  private Optional<String> _getSupplementaryUnit() {
    return supplementaryUnit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("supplementaryQtyPerUnit")
  private Optional<String> _getSupplementaryQtyPerUnit() {
    return supplementaryQtyPerUnit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("groupId")
  private Optional<String> _getGroupId() {
    return groupId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("attributes")
  private Optional<Map<String, Optional<String>>> _getAttributes() {
    return attributes;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("translations")
  private Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> _getTranslations(
      ) {
    return translations;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1CatalogItemsGetResponse && equalTo((PostV1CatalogItemsGetResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1CatalogItemsGetResponse other) {
    return id.equals(other.id) && type.equals(other.type) && name.equals(other.name) && code.equals(other.code) && barcode.equals(other.barcode) && unit.equals(other.unit) && vatClassifierCode.equals(other.vatClassifierCode) && vatRatePercent.equals(other.vatRatePercent) && salePriceExclVat.equals(other.salePriceExclVat) && purchasePriceExclVat.equals(other.purchasePriceExclVat) && cnCode.equals(other.cnCode) && originCountry.equals(other.originCountry) && netMassKg.equals(other.netMassKg) && supplementaryUnit.equals(other.supplementaryUnit) && supplementaryQtyPerUnit.equals(other.supplementaryQtyPerUnit) && description.equals(other.description) && groupId.equals(other.groupId) && attributes.equals(other.attributes) && translations.equals(other.translations) && components.equals(other.components) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.type, this.name, this.code, this.barcode, this.unit, this.vatClassifierCode, this.vatRatePercent, this.salePriceExclVat, this.purchasePriceExclVat, this.cnCode, this.originCountry, this.netMassKg, this.supplementaryUnit, this.supplementaryQtyPerUnit, this.description, this.groupId, this.attributes, this.translations, this.components, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    TypeStage id(@NotNull String id);

    Builder from(PostV1CatalogItemsGetResponse other);
  }

  public interface TypeStage {
    NameStage type(@NotNull PostV1CatalogItemsGetResponseType type);
  }

  public interface NameStage {
    UnitStage name(@NotNull String name);
  }

  public interface UnitStage {
    CreatedAtStage unit(@NotNull String unit);
  }

  public interface CreatedAtStage {
    UpdatedAtStage createdAt(@NotNull String createdAt);
  }

  public interface UpdatedAtStage {
    _FinalStage updatedAt(@NotNull String updatedAt);
  }

  public interface _FinalStage {
    PostV1CatalogItemsGetResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage code(Optional<String> code);

    _FinalStage code(String code);

    _FinalStage code(Nullable<String> code);

    _FinalStage barcode(Optional<String> barcode);

    _FinalStage barcode(String barcode);

    _FinalStage barcode(Nullable<String> barcode);

    _FinalStage vatClassifierCode(Optional<String> vatClassifierCode);

    _FinalStage vatClassifierCode(String vatClassifierCode);

    _FinalStage vatClassifierCode(Nullable<String> vatClassifierCode);

    _FinalStage vatRatePercent(Optional<String> vatRatePercent);

    _FinalStage vatRatePercent(String vatRatePercent);

    _FinalStage vatRatePercent(Nullable<String> vatRatePercent);

    _FinalStage salePriceExclVat(Optional<String> salePriceExclVat);

    _FinalStage salePriceExclVat(String salePriceExclVat);

    _FinalStage salePriceExclVat(Nullable<String> salePriceExclVat);

    _FinalStage purchasePriceExclVat(Optional<String> purchasePriceExclVat);

    _FinalStage purchasePriceExclVat(String purchasePriceExclVat);

    _FinalStage purchasePriceExclVat(Nullable<String> purchasePriceExclVat);

    _FinalStage cnCode(Optional<String> cnCode);

    _FinalStage cnCode(String cnCode);

    _FinalStage cnCode(Nullable<String> cnCode);

    _FinalStage originCountry(Optional<String> originCountry);

    _FinalStage originCountry(String originCountry);

    _FinalStage originCountry(Nullable<String> originCountry);

    _FinalStage netMassKg(Optional<String> netMassKg);

    _FinalStage netMassKg(String netMassKg);

    _FinalStage netMassKg(Nullable<String> netMassKg);

    _FinalStage supplementaryUnit(Optional<String> supplementaryUnit);

    _FinalStage supplementaryUnit(String supplementaryUnit);

    _FinalStage supplementaryUnit(Nullable<String> supplementaryUnit);

    _FinalStage supplementaryQtyPerUnit(Optional<String> supplementaryQtyPerUnit);

    _FinalStage supplementaryQtyPerUnit(String supplementaryQtyPerUnit);

    _FinalStage supplementaryQtyPerUnit(Nullable<String> supplementaryQtyPerUnit);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage groupId(Optional<String> groupId);

    _FinalStage groupId(String groupId);

    _FinalStage groupId(Nullable<String> groupId);

    _FinalStage attributes(Optional<Map<String, Optional<String>>> attributes);

    _FinalStage attributes(Map<String, Optional<String>> attributes);

    _FinalStage attributes(Nullable<Map<String, Optional<String>>> attributes);

    _FinalStage translations(
        Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations);

    _FinalStage translations(
        Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>> translations);

    _FinalStage translations(
        Nullable<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations);

    _FinalStage components(List<PostV1CatalogItemsGetResponseComponentsItem> components);

    _FinalStage addComponents(PostV1CatalogItemsGetResponseComponentsItem components);

    _FinalStage addAllComponents(List<PostV1CatalogItemsGetResponseComponentsItem> components);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, TypeStage, NameStage, UnitStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
    private String id;

    private PostV1CatalogItemsGetResponseType type;

    private String name;

    private String unit;

    private String createdAt;

    private String updatedAt;

    private List<PostV1CatalogItemsGetResponseComponentsItem> components = new ArrayList<>();

    private Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations = Optional.empty();

    private Optional<Map<String, Optional<String>>> attributes = Optional.empty();

    private Optional<String> groupId = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> supplementaryQtyPerUnit = Optional.empty();

    private Optional<String> supplementaryUnit = Optional.empty();

    private Optional<String> netMassKg = Optional.empty();

    private Optional<String> originCountry = Optional.empty();

    private Optional<String> cnCode = Optional.empty();

    private Optional<String> purchasePriceExclVat = Optional.empty();

    private Optional<String> salePriceExclVat = Optional.empty();

    private Optional<String> vatRatePercent = Optional.empty();

    private Optional<String> vatClassifierCode = Optional.empty();

    private Optional<String> barcode = Optional.empty();

    private Optional<String> code = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1CatalogItemsGetResponse other) {
      id(other.getId());
      type(other.getType());
      name(other.getName());
      code(other.getCode());
      barcode(other.getBarcode());
      unit(other.getUnit());
      vatClassifierCode(other.getVatClassifierCode());
      vatRatePercent(other.getVatRatePercent());
      salePriceExclVat(other.getSalePriceExclVat());
      purchasePriceExclVat(other.getPurchasePriceExclVat());
      cnCode(other.getCnCode());
      originCountry(other.getOriginCountry());
      netMassKg(other.getNetMassKg());
      supplementaryUnit(other.getSupplementaryUnit());
      supplementaryQtyPerUnit(other.getSupplementaryQtyPerUnit());
      description(other.getDescription());
      groupId(other.getGroupId());
      attributes(other.getAttributes());
      translations(other.getTranslations());
      components(other.getComponents());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public TypeStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public NameStage type(@NotNull PostV1CatalogItemsGetResponseType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public UnitStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("unit")
    public CreatedAtStage unit(@NotNull String unit) {
      this.unit = Objects.requireNonNull(unit, "unit must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public UpdatedAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updatedAt")
    public _FinalStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllComponents(
        List<PostV1CatalogItemsGetResponseComponentsItem> components) {
      if (components != null) {
        this.components.addAll(components);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addComponents(PostV1CatalogItemsGetResponseComponentsItem components) {
      this.components.add(components);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "components",
        nulls = Nulls.SKIP
    )
    public _FinalStage components(List<PostV1CatalogItemsGetResponseComponentsItem> components) {
      this.components.clear();
      if (components != null) {
        this.components.addAll(components);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage translations(
        Nullable<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations) {
      if (translations.isNull()) {
        this.translations = null;
      }
      else if (translations.isEmpty()) {
        this.translations = Optional.empty();
      }
      else {
        this.translations = Optional.of(translations.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage translations(
        Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>> translations) {
      this.translations = Optional.ofNullable(translations);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "translations",
        nulls = Nulls.SKIP
    )
    public _FinalStage translations(
        Optional<Map<String, Optional<PostV1CatalogItemsGetResponseTranslationsValue>>> translations) {
      this.translations = translations;
      return this;
    }

    @java.lang.Override
    public _FinalStage attributes(Nullable<Map<String, Optional<String>>> attributes) {
      if (attributes.isNull()) {
        this.attributes = null;
      }
      else if (attributes.isEmpty()) {
        this.attributes = Optional.empty();
      }
      else {
        this.attributes = Optional.of(attributes.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage attributes(Map<String, Optional<String>> attributes) {
      this.attributes = Optional.ofNullable(attributes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "attributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage attributes(Optional<Map<String, Optional<String>>> attributes) {
      this.attributes = attributes;
      return this;
    }

    @java.lang.Override
    public _FinalStage groupId(Nullable<String> groupId) {
      if (groupId.isNull()) {
        this.groupId = null;
      }
      else if (groupId.isEmpty()) {
        this.groupId = Optional.empty();
      }
      else {
        this.groupId = Optional.of(groupId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage groupId(String groupId) {
      this.groupId = Optional.ofNullable(groupId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "groupId",
        nulls = Nulls.SKIP
    )
    public _FinalStage groupId(Optional<String> groupId) {
      this.groupId = groupId;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public _FinalStage supplementaryQtyPerUnit(Nullable<String> supplementaryQtyPerUnit) {
      if (supplementaryQtyPerUnit.isNull()) {
        this.supplementaryQtyPerUnit = null;
      }
      else if (supplementaryQtyPerUnit.isEmpty()) {
        this.supplementaryQtyPerUnit = Optional.empty();
      }
      else {
        this.supplementaryQtyPerUnit = Optional.of(supplementaryQtyPerUnit.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage supplementaryQtyPerUnit(String supplementaryQtyPerUnit) {
      this.supplementaryQtyPerUnit = Optional.ofNullable(supplementaryQtyPerUnit);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "supplementaryQtyPerUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage supplementaryQtyPerUnit(Optional<String> supplementaryQtyPerUnit) {
      this.supplementaryQtyPerUnit = supplementaryQtyPerUnit;
      return this;
    }

    @java.lang.Override
    public _FinalStage supplementaryUnit(Nullable<String> supplementaryUnit) {
      if (supplementaryUnit.isNull()) {
        this.supplementaryUnit = null;
      }
      else if (supplementaryUnit.isEmpty()) {
        this.supplementaryUnit = Optional.empty();
      }
      else {
        this.supplementaryUnit = Optional.of(supplementaryUnit.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage supplementaryUnit(String supplementaryUnit) {
      this.supplementaryUnit = Optional.ofNullable(supplementaryUnit);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "supplementaryUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage supplementaryUnit(Optional<String> supplementaryUnit) {
      this.supplementaryUnit = supplementaryUnit;
      return this;
    }

    @java.lang.Override
    public _FinalStage netMassKg(Nullable<String> netMassKg) {
      if (netMassKg.isNull()) {
        this.netMassKg = null;
      }
      else if (netMassKg.isEmpty()) {
        this.netMassKg = Optional.empty();
      }
      else {
        this.netMassKg = Optional.of(netMassKg.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage netMassKg(String netMassKg) {
      this.netMassKg = Optional.ofNullable(netMassKg);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "netMassKg",
        nulls = Nulls.SKIP
    )
    public _FinalStage netMassKg(Optional<String> netMassKg) {
      this.netMassKg = netMassKg;
      return this;
    }

    @java.lang.Override
    public _FinalStage originCountry(Nullable<String> originCountry) {
      if (originCountry.isNull()) {
        this.originCountry = null;
      }
      else if (originCountry.isEmpty()) {
        this.originCountry = Optional.empty();
      }
      else {
        this.originCountry = Optional.of(originCountry.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage originCountry(String originCountry) {
      this.originCountry = Optional.ofNullable(originCountry);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "originCountry",
        nulls = Nulls.SKIP
    )
    public _FinalStage originCountry(Optional<String> originCountry) {
      this.originCountry = originCountry;
      return this;
    }

    @java.lang.Override
    public _FinalStage cnCode(Nullable<String> cnCode) {
      if (cnCode.isNull()) {
        this.cnCode = null;
      }
      else if (cnCode.isEmpty()) {
        this.cnCode = Optional.empty();
      }
      else {
        this.cnCode = Optional.of(cnCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage cnCode(String cnCode) {
      this.cnCode = Optional.ofNullable(cnCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "cnCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage cnCode(Optional<String> cnCode) {
      this.cnCode = cnCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasePriceExclVat(Nullable<String> purchasePriceExclVat) {
      if (purchasePriceExclVat.isNull()) {
        this.purchasePriceExclVat = null;
      }
      else if (purchasePriceExclVat.isEmpty()) {
        this.purchasePriceExclVat = Optional.empty();
      }
      else {
        this.purchasePriceExclVat = Optional.of(purchasePriceExclVat.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage purchasePriceExclVat(String purchasePriceExclVat) {
      this.purchasePriceExclVat = Optional.ofNullable(purchasePriceExclVat);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "purchasePriceExclVat",
        nulls = Nulls.SKIP
    )
    public _FinalStage purchasePriceExclVat(Optional<String> purchasePriceExclVat) {
      this.purchasePriceExclVat = purchasePriceExclVat;
      return this;
    }

    @java.lang.Override
    public _FinalStage salePriceExclVat(Nullable<String> salePriceExclVat) {
      if (salePriceExclVat.isNull()) {
        this.salePriceExclVat = null;
      }
      else if (salePriceExclVat.isEmpty()) {
        this.salePriceExclVat = Optional.empty();
      }
      else {
        this.salePriceExclVat = Optional.of(salePriceExclVat.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage salePriceExclVat(String salePriceExclVat) {
      this.salePriceExclVat = Optional.ofNullable(salePriceExclVat);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "salePriceExclVat",
        nulls = Nulls.SKIP
    )
    public _FinalStage salePriceExclVat(Optional<String> salePriceExclVat) {
      this.salePriceExclVat = salePriceExclVat;
      return this;
    }

    @java.lang.Override
    public _FinalStage vatRatePercent(Nullable<String> vatRatePercent) {
      if (vatRatePercent.isNull()) {
        this.vatRatePercent = null;
      }
      else if (vatRatePercent.isEmpty()) {
        this.vatRatePercent = Optional.empty();
      }
      else {
        this.vatRatePercent = Optional.of(vatRatePercent.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage vatRatePercent(String vatRatePercent) {
      this.vatRatePercent = Optional.ofNullable(vatRatePercent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "vatRatePercent",
        nulls = Nulls.SKIP
    )
    public _FinalStage vatRatePercent(Optional<String> vatRatePercent) {
      this.vatRatePercent = vatRatePercent;
      return this;
    }

    @java.lang.Override
    public _FinalStage vatClassifierCode(Nullable<String> vatClassifierCode) {
      if (vatClassifierCode.isNull()) {
        this.vatClassifierCode = null;
      }
      else if (vatClassifierCode.isEmpty()) {
        this.vatClassifierCode = Optional.empty();
      }
      else {
        this.vatClassifierCode = Optional.of(vatClassifierCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage vatClassifierCode(String vatClassifierCode) {
      this.vatClassifierCode = Optional.ofNullable(vatClassifierCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "vatClassifierCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage vatClassifierCode(Optional<String> vatClassifierCode) {
      this.vatClassifierCode = vatClassifierCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage barcode(Nullable<String> barcode) {
      if (barcode.isNull()) {
        this.barcode = null;
      }
      else if (barcode.isEmpty()) {
        this.barcode = Optional.empty();
      }
      else {
        this.barcode = Optional.of(barcode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage barcode(String barcode) {
      this.barcode = Optional.ofNullable(barcode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "barcode",
        nulls = Nulls.SKIP
    )
    public _FinalStage barcode(Optional<String> barcode) {
      this.barcode = barcode;
      return this;
    }

    @java.lang.Override
    public _FinalStage code(Nullable<String> code) {
      if (code.isNull()) {
        this.code = null;
      }
      else if (code.isEmpty()) {
        this.code = Optional.empty();
      }
      else {
        this.code = Optional.of(code.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage code(String code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public _FinalStage code(Optional<String> code) {
      this.code = code;
      return this;
    }

    @java.lang.Override
    public PostV1CatalogItemsGetResponse build() {
      return new PostV1CatalogItemsGetResponse(id, type, name, code, barcode, unit, vatClassifierCode, vatRatePercent, salePriceExclVat, purchasePriceExclVat, cnCode, originCountry, netMassKg, supplementaryUnit, supplementaryQtyPerUnit, description, groupId, attributes, translations, components, createdAt, updatedAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
