/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.nordlet.api.resources.migration.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nordlet.api.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1MigrationBooksImportRequestJournalItem.Builder.class
)
public final class PostV1MigrationBooksImportRequestJournalItem {
  private final String date;

  private final Optional<String> description;

  private final Optional<String> reference;

  private final List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries;

  private final Map<String, Object> additionalProperties;

  private PostV1MigrationBooksImportRequestJournalItem(String date, Optional<String> description,
      Optional<String> reference,
      List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries,
      Map<String, Object> additionalProperties) {
    this.date = date;
    this.description = description;
    this.reference = reference;
    this.entries = entries;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("date")
  public String getDate() {
    return date;
  }

  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  @JsonProperty("reference")
  public Optional<String> getReference() {
    return reference;
  }

  @JsonProperty("entries")
  public List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> getEntries() {
    return entries;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1MigrationBooksImportRequestJournalItem && equalTo((PostV1MigrationBooksImportRequestJournalItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1MigrationBooksImportRequestJournalItem other) {
    return date.equals(other.date) && description.equals(other.description) && reference.equals(other.reference) && entries.equals(other.entries);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.date, this.description, this.reference, this.entries);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DateStage builder() {
    return new Builder();
  }

  public interface DateStage {
    _FinalStage date(@NotNull String date);

    Builder from(PostV1MigrationBooksImportRequestJournalItem other);
  }

  public interface _FinalStage {
    PostV1MigrationBooksImportRequestJournalItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage reference(Optional<String> reference);

    _FinalStage reference(String reference);

    _FinalStage entries(List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries);

    _FinalStage addEntries(PostV1MigrationBooksImportRequestJournalItemEntriesItem entries);

    _FinalStage addAllEntries(
        List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DateStage, _FinalStage {
    private String date;

    private List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries = new ArrayList<>();

    private Optional<String> reference = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1MigrationBooksImportRequestJournalItem other) {
      date(other.getDate());
      description(other.getDescription());
      reference(other.getReference());
      entries(other.getEntries());
      return this;
    }

    @java.lang.Override
    @JsonSetter("date")
    public _FinalStage date(@NotNull String date) {
      this.date = Objects.requireNonNull(date, "date must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllEntries(
        List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries) {
      if (entries != null) {
        this.entries.addAll(entries);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addEntries(PostV1MigrationBooksImportRequestJournalItemEntriesItem entries) {
      this.entries.add(entries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "entries",
        nulls = Nulls.SKIP
    )
    public _FinalStage entries(
        List<PostV1MigrationBooksImportRequestJournalItemEntriesItem> entries) {
      this.entries.clear();
      if (entries != null) {
        this.entries.addAll(entries);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage reference(String reference) {
      this.reference = Optional.ofNullable(reference);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "reference",
        nulls = Nulls.SKIP
    )
    public _FinalStage reference(Optional<String> reference) {
      this.reference = reference;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public PostV1MigrationBooksImportRequestJournalItem build() {
      return new PostV1MigrationBooksImportRequestJournalItem(date, description, reference, entries, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
