/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1DeclarationsConfigsUpdateResponseEndpointsItem.Builder.class
)
public final class PostV1DeclarationsConfigsUpdateResponseEndpointsItem {
  private final String name;

  private final Optional<String> test;

  private final Optional<String> production;

  private final Map<String, Object> additionalProperties;

  private PostV1DeclarationsConfigsUpdateResponseEndpointsItem(String name, Optional<String> test,
      Optional<String> production, Map<String, Object> additionalProperties) {
    this.name = name;
    this.test = test;
    this.production = production;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("test")
  public Optional<String> getTest() {
    return test;
  }

  @JsonProperty("production")
  public Optional<String> getProduction() {
    return production;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1DeclarationsConfigsUpdateResponseEndpointsItem && equalTo((PostV1DeclarationsConfigsUpdateResponseEndpointsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1DeclarationsConfigsUpdateResponseEndpointsItem other) {
    return name.equals(other.name) && test.equals(other.test) && production.equals(other.production);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.test, this.production);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    _FinalStage name(@NotNull String name);

    Builder from(PostV1DeclarationsConfigsUpdateResponseEndpointsItem other);
  }

  public interface _FinalStage {
    PostV1DeclarationsConfigsUpdateResponseEndpointsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage test(Optional<String> test);

    _FinalStage test(String test);

    _FinalStage production(Optional<String> production);

    _FinalStage production(String production);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, _FinalStage {
    private String name;

    private Optional<String> production = Optional.empty();

    private Optional<String> test = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1DeclarationsConfigsUpdateResponseEndpointsItem other) {
      name(other.getName());
      test(other.getTest());
      production(other.getProduction());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public _FinalStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage production(String production) {
      this.production = Optional.ofNullable(production);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "production",
        nulls = Nulls.SKIP
    )
    public _FinalStage production(Optional<String> production) {
      this.production = production;
      return this;
    }

    @java.lang.Override
    public _FinalStage test(String test) {
      this.test = Optional.ofNullable(test);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "test",
        nulls = Nulls.SKIP
    )
    public _FinalStage test(Optional<String> test) {
      this.test = test;
      return this;
    }

    @java.lang.Override
    public PostV1DeclarationsConfigsUpdateResponseEndpointsItem build() {
      return new PostV1DeclarationsConfigsUpdateResponseEndpointsItem(name, test, production, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
