/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.declarations.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem.Builder.class
)
public final class PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem {
  private final PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection direction;

  private final Optional<String> taxCode;

  private final String net;

  private final String vat;

  private final List<String> taxableFields;

  private final List<String> vatFields;

  private final Map<String, Object> additionalProperties;

  private PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem(
      PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection direction,
      Optional<String> taxCode, String net, String vat, List<String> taxableFields,
      List<String> vatFields, Map<String, Object> additionalProperties) {
    this.direction = direction;
    this.taxCode = taxCode;
    this.net = net;
    this.vat = vat;
    this.taxableFields = taxableFields;
    this.vatFields = vatFields;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("direction")
  public PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection getDirection() {
    return direction;
  }

  @JsonIgnore
  public Optional<String> getTaxCode() {
    if (taxCode == null) {
      return Optional.empty();
    }
    return taxCode;
  }

  @JsonProperty("net")
  public String getNet() {
    return net;
  }

  @JsonProperty("vat")
  public String getVat() {
    return vat;
  }

  @JsonProperty("taxableFields")
  public List<String> getTaxableFields() {
    return taxableFields;
  }

  @JsonProperty("vatFields")
  public List<String> getVatFields() {
    return vatFields;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("taxCode")
  private Optional<String> _getTaxCode() {
    return taxCode;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem && equalTo((PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem other) {
    return direction.equals(other.direction) && taxCode.equals(other.taxCode) && net.equals(other.net) && vat.equals(other.vat) && taxableFields.equals(other.taxableFields) && vatFields.equals(other.vatFields);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.direction, this.taxCode, this.net, this.vat, this.taxableFields, this.vatFields);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DirectionStage builder() {
    return new Builder();
  }

  public interface DirectionStage {
    NetStage direction(
        @NotNull PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection direction);

    Builder from(PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem other);
  }

  public interface NetStage {
    VatStage net(@NotNull String net);
  }

  public interface VatStage {
    _FinalStage vat(@NotNull String vat);
  }

  public interface _FinalStage {
    PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage taxCode(Optional<String> taxCode);

    _FinalStage taxCode(String taxCode);

    _FinalStage taxCode(Nullable<String> taxCode);

    _FinalStage taxableFields(List<String> taxableFields);

    _FinalStage addTaxableFields(String taxableFields);

    _FinalStage addAllTaxableFields(List<String> taxableFields);

    _FinalStage vatFields(List<String> vatFields);

    _FinalStage addVatFields(String vatFields);

    _FinalStage addAllVatFields(List<String> vatFields);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DirectionStage, NetStage, VatStage, _FinalStage {
    private PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection direction;

    private String net;

    private String vat;

    private List<String> vatFields = new ArrayList<>();

    private List<String> taxableFields = new ArrayList<>();

    private Optional<String> taxCode = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem other) {
      direction(other.getDirection());
      taxCode(other.getTaxCode());
      net(other.getNet());
      vat(other.getVat());
      taxableFields(other.getTaxableFields());
      vatFields(other.getVatFields());
      return this;
    }

    @java.lang.Override
    @JsonSetter("direction")
    public NetStage direction(
        @NotNull PostV1DeclarationsLtFr0600ComputeResponseBreakdownItemDirection direction) {
      this.direction = Objects.requireNonNull(direction, "direction must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("net")
    public VatStage net(@NotNull String net) {
      this.net = Objects.requireNonNull(net, "net must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("vat")
    public _FinalStage vat(@NotNull String vat) {
      this.vat = Objects.requireNonNull(vat, "vat must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllVatFields(List<String> vatFields) {
      if (vatFields != null) {
        this.vatFields.addAll(vatFields);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addVatFields(String vatFields) {
      this.vatFields.add(vatFields);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "vatFields",
        nulls = Nulls.SKIP
    )
    public _FinalStage vatFields(List<String> vatFields) {
      this.vatFields.clear();
      if (vatFields != null) {
        this.vatFields.addAll(vatFields);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllTaxableFields(List<String> taxableFields) {
      if (taxableFields != null) {
        this.taxableFields.addAll(taxableFields);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addTaxableFields(String taxableFields) {
      this.taxableFields.add(taxableFields);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "taxableFields",
        nulls = Nulls.SKIP
    )
    public _FinalStage taxableFields(List<String> taxableFields) {
      this.taxableFields.clear();
      if (taxableFields != null) {
        this.taxableFields.addAll(taxableFields);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage taxCode(Nullable<String> taxCode) {
      if (taxCode.isNull()) {
        this.taxCode = null;
      }
      else if (taxCode.isEmpty()) {
        this.taxCode = Optional.empty();
      }
      else {
        this.taxCode = Optional.of(taxCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage taxCode(String taxCode) {
      this.taxCode = Optional.ofNullable(taxCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "taxCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage taxCode(Optional<String> taxCode) {
      this.taxCode = taxCode;
      return this;
    }

    @java.lang.Override
    public PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem build() {
      return new PostV1DeclarationsLtFr0600ComputeResponseBreakdownItem(direction, taxCode, net, vat, taxableFields, vatFields, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
